dandi/dandi-cli

dandi/pynwb_utils.py
dandi/tests/test_pynwb_utils.py
setup.cfg
setup.py

the latest pynwb 1.1.0 is having issues, but this works with `pynwb==1.0.3` and `hdmf==1.2.0`.

add pynwb get_metadata

---

.github/workflows/test.yml
dandi/pynwb_utils.py
dandi/tests/fixtures.py
dandi/tests/test_pynwb_utils.py
setup.cfg

Let's see if this beast (github workflows) works!

ENH: Fixed up **the** test to pass, added basic github workflow

---

README.md
dandi/cli/command.py
dandi/cli/formatter.py
dandi/girder.py
dandi/pynwb_utils.py
dandi/support/generatorify.py
dandi/support/pyout.py
dandi/utils.py
setup.cfg

Somewhat reimplemented so far what possibly girder client could have done for us already
-  test(s) -- dedicated #27 for that

NF: upload

---

README.md
dandi/cli/command.py
dandi/cli/formatter.py
dandi/girder.py
dandi/pynwb_utils.py
dandi/support/generatorify.py
dandi/support/pyout.py
dandi/utils.py
setup.cfg

sits on top of #26 since that one defined the function which this PR changes in 9f2178f7005484da32412e638b75d33ac23dc4c1
Closes #22

ENH: ignore some (incorrect) validation errors

---

README.md
dandi/cli/command.py
dandi/cli/formatter.py
dandi/girder.py
dandi/pynwb_utils.py
dandi/support/generatorify.py
dandi/support/pyout.py
dandi/utils.py
setup.cfg

sits on top of #28 which is on top of #26

ENH: ls -- temp workaround for pyout issue to be fixed, min bound path width

---

dandi/tests/test_organize.py

apparently with current setup cannot submit PRs from my own fork and have their coverage reported : https://github.com/dandi/dandi-cli/pull/39 :-( that is suboptimal
testing by submitting withing our repo - must work

ENH(TST): initial test for sanitize_value

---

dandi/download.py

i'm going to redirect the permalink to the dandiset landing page. before i can do that, the cli should be able to download from that URL.

enh: allow downloading from a dandiset landing page

---

dandi/tests/test_utils.py
dandi/utils.py

BF: by default exclude all dot files from find_files results

---

.et
dandi/__init__.py
dandi/cli/tests/test_command.py
setup.cfg

@yarikoptic - let me know if you want this check in some other form
@mgrauer - this is a bit of boilerplate that should be moved into etelemetry itself. we have just been lazy!!

enh: add etelemetry to dandi cli

---

setup.py

ENH: raise RuntimeError with informative msg when using python2 on setup.py

---

dandi/cli/tests/test_command.py
dandi/support/cache.py
dandi/support/tests/test_cache.py
dandi/tests/test_validate.py
dandi/validate.py

This is a quick enhancement, proper solution is still WiP (using schemas etc).

ENH: validate - should now detect absent (or degenerate) subject_id field

---

dandi/download.py
dandi/tests/test_utils.py
dandi/utils.py

Not yet sure exactly what lead to it, but clearly flattening was not recursive enough.  Fixed now.  Closes #83

BF: download - tolerate getting a generator listing the items

---

dandi/cli/cmd_download.py
dandi/download.py

if works -- why not? ;)  `-J 1` will still cause use of joblib but should avoid parallel execution (whenever needed)
edit : there is no overall progress or ETA yet... might come later (or not)

ENH: a very basic implementation of parallel download

---

dandi/tests/test_validate.py
dandi/validate.py

ENH: validate - make robust against problems loading metadata

---

dandi/__init__.py
dandi/cli/command.py
dandi/download.py

move etelemetry to main

---

dandi/download.py
dandi/tests/test_download.py

and add support for arbitrary redirectors.  Closes: #99 
After https://github.com/dandi/redirector/issues/13 resolved ad-hoc kludge could go away

ENH+OPT: Issue HEAD not GET while checking redirects (whenever we can)

---

dandi/cli/cmd_organize.py
dandi/cli/command.py
dandi/organize.py

organize: BF - do not consider also empty lists etc + ENH -- devel-debug to disable Parallel

---

dandi/cli/cmd_upload.py
dandi/cli/command.py

See individual commits, complement to now merged #137

ENH: more/better logging

---

.github/workflows/test.yml
setup.cfg

Also, add the Python 3.8 classifier
Closes #143

Configure CI to test under Python 3.8

---

.github/workflows/lint.yml

PR #144 is a prerequisite for this.  (In the future, when PR x depends on PR y, would you prefer it if x's branch extended y's or not?)

Configure CI to run flake8

---

DEVELOPMENT.md

Document Sourcegraph in DEVELOPMENT.md

---

dandi/tests/fixtures.py
dandi/tests/test_register.py

Everything after bringing the containers up should be inside a `try` with a `finally` that brings them down.

Put more of local_docker_compose inside `try`

---

dandi/cli/cmd_register.py
dandi/register.py
dandi/tests/fixtures.py
dandi/tests/test_register.py
dandi/tests/test_upload.py

This PR includes the changes in #175 in order to make use of the new "identifier_id" key.
Closes #173.

register(): Adjust dandi_instance argument

---

dandi/cli/command.py

map_to_click_exceptions: Convert gcl.HttpErrors to their "message" fields

---

pytest.ini
tox.ini

individual commits have more reasoning described.

ENH: pytest.ini

---

dandi/cli/base.py
dandi/cli/cmd_download.py
dandi/cli/cmd_ls.py
dandi/cli/cmd_organize.py
dandi/cli/cmd_register.py
dandi/cli/cmd_upload.py
dandi/cli/cmd_validate.py
dandi/cli/command.py
dandi/upload.py

Break circular imports

---

dandi/download.py
dandi/tests/test_download.py

RF+BF: download - fixup download of drafts on Windows

---

dandi/organize.py
dandi/tests/test_organize.py

Not sure why unit-tests did not blow before.
I think it Closes #204

BF: use os.path.join while joining directory and filename in organize

---

dandi/cli/cmd_organize.py
dandi/consts.py
dandi/organize.py
dandi/tests/test_organize.py

organize: Set default of -f to "auto" for link-type autodetection

---

dandi/cli/cmd_download.py
dandi/cli/tests/test_download.py
dandi/download.py
dandi/tests/test_download.py

Give download an option for only downloading dandiset.yaml/assets

---

dandi/cli/command.py
dandi/cli/tests/test_command.py

Primarily a smoke test for options rendering etc.

ENH(TST): add a very basic test for all commands providing some --help

---

dandi/tests/test_upload.py

Make filepaths OS-agnostic

---

dandi/upload.py

TODO
-  confirm failing on windows -- impossible in tests ATM

BF/RF: upload - Path for file paths, and PurePosixPath for anything dealing with girder

---

dandi/support/tests/test_iterators.py

BF(TST): detect slow machine (e.g. Win7 VM) and increase sleeps for such case to 0.1

---

dandi/support/tests/test_cache.py
dandi/tests/test_organize.py

I don't have a Windows machine to test this on, but I expect it'll work.
This PR does NOT contain a fix for the bug I pointed out in the comments of #213.
I don't know why `test_IteratorWithAggregation` was failing, so this PR does not address it.
Fixes #213.

Handle symlinks in tests on Windows

---

dandi/cli/cmd_ls.py

See individual commit messages for more info

BF+ENH: do not puke while flattening and allow to work on broken links

---

dandi/tests/test_upload.py
dandi/upload.py

Increase coverage of upload.py

---

dandi/support/tests/test_cache.py

This PR applies the fixes I suggested in [this comment](https://github.com/dandi/dandi-cli/issues/213#issuecomment-680996204).

Fix bugs in test_memoize_path

---

dandi/girder.py
dandi/tests/test_girder.py

ENH: provide original exception message while preparing LockingError exception

---

tools/instantiate-dandisets.py

Script for "instantiating" Dandisets from asset store

---

dandi/dandiapi.py
dandi/download.py
dandi/girder.py
dandi/tests/test_download.py
setup.cfg

Download files to temporary directory containing metadata

---

tools/backups2datalad.py

This change wasn't made in time before #251 was merged.

backup2datalad.py: Store complete asset metadata in .dandi/assets.json

---

CHANGELOG.md

Remove unused link from CHANGELOG.md

---

dandi/utils.py

Copy files with `cp --reflink=auto` where supported

---

dandi/girder.py

Include item path in "Multiple files found for item" message

---

dandi/pynwb_utils.py
setup.cfg
tox.ini

Support h5py 3.0

---

.github/workflows/publish-schemata.yml
tools/pubschemata.py

Add workflow for publishing model schemata to dandi/schema

---

.github/workflows/publish-schemata.yml

Fix publish-schemata workflow

---

.github/workflows/publish-schemata.yml

Closes #289 again (hopefully for good).

Fix more of publish-schemata workflow

---

dandi/tests/test_upload.py
dandi/upload.py

Compare uploaded file size against what download headers report

---

dandi/girder.py
dandi/upload.py

Set chunk size on per-file basis; limit to 1000 chunks; upload files up to 400GB ATM

---

dandi/tests/fixtures.py

In case something like [this](https://github.com/dandi/dandi-cli/issues/322#issuecomment-748299005) ever happens again.

Fetch Django test API token more robustly

---

dandi/metadata.py

Fixes #328.
(I also simplified the surrounding code a little bit.)

Fix `AttributeError: 'Resource' object has no attribute 'values'`

---

dandi/girder.py
dandi/utils.py

Try self.listFile() again on ConnectionErrors

---

setup.cfg

Sort install_requires

---

DEVELOPMENT.md
dandi/tests/fixtures.py

Add DANDI_TESTS_PERSIST_DOCKER_COMPOSE envvar for reusing Docker containers across test runs

---

dandi/metadata.py
dandi/tests/test_metadata.py

Adjust license metadata conversion

---

tools/migrate-dandisets.py

Add script for migrating Dandiset metadata

---

dandi/consts.py
dandi/dandiarchive.py
dandi/download.py
dandi/tests/test_dandiapi.py
dandi/tests/test_dandiarchive.py
dandi/tests/test_download.py

Support downloading folders and latest Dandiset version

---

dandi/consts.py
dandi/dandiarchive.py
dandi/download.py
dandi/tests/fixtures.py
dandi/tests/test_dandiapi.py
dandi/tests/test_dandiarchive.py
dandi/tests/test_download.py
dandi/tests/test_upload.py

This change allows us to cut down on a bunch of duplicate code in the tests.
This PR is built on top of #377.  Only the last commit is specific to this branch.

Add sample Dandiset test fixture

---

dandi/dandiapi.py
dandi/tests/test_dandiapi.py
dandi/upload.py

Merge if & only if https://github.com/dandi/dandi-api/pull/105 has been merged.
Replaces #371.

Set asset path via metadata only

---

dandi/dandiarchive.py

This PR associates each entry in `known_urls` with a string describing the pattern that should be more readable than the regexes themselves; the strings are then used in place of the regexes in the exception message when raising `UnknownURLError`.
The PR also reformats the `known_urls` source to be, in my opinion, more readable.

Give known_urls human-readable display strings

---

dandi/dandiapi.py
dandi/upload.py

Use PUT endpoint to replace pre-existing assets on upload

---

.github/workflows/test.yml

Add CI run with dev version of pynwb

---

dandi/cli/formatter.py
dandi/download.py
dandi/support/pyout.py
dandi/upload.py

Disabling logging to stderr while using pyout

---

.github/workflows/test-populate-dandiset-yaml.yml

@yarikoptic - let's see if this works.

FIX: use authorized checkout for actions

---

dandi/metadata.py
dandi/tests/test_metadata.py

Closes #385.
I am marking this as a draft because further edits will be necessary if & when #373 is merged.

Populate wasDerivedFrom

---

dandi/dandiapi.py

Add more logging when uploading & downloading

---

dandi/dandiapi.py
dandi/tests/test_dandiapi.py

Set Content-MD5 header when uploading asset parts

---

dandi/upload.py

upload(): Only yield first "validating" status to pyout

---

dandi/download.py

Error if sha256 digest is missing from asset being downloaded

---

dandi/metadata.py
dandi/models.py
dandi/tests/test_validate.py
dandi/validate.py

Closes #430.
After merging this, merge https://github.com/dandi/dandi-api-datasets/pull/18.

Eliminate DANDI_SCHEMA; add get_schema_version()

---

dandi/metadata.py

Eliminate check for session_start_time preceding date_of_birth

---

dandi/pynwb_utils.py
dandi/validate.py

As requested [here](https://github.com/dandi/dandi-api-datasets/pull/18#discussion_r585034776).

Cache the individual functions called by validate_file()

---

.github/workflows/release.yml

[As requested by an `auto` developer](https://github.com/intuit/auto/issues/1860#issuecomment-797827132) for debugging an issue with our last release.

Add `-vv` option to `auto shipit`

---

dandi/consts.py
dandi/dandiapi.py
dandi/metadata.py
dandi/models.py
dandi/tests/test_metadata.py

Change BareAssetMeta.digest to a list

---

dandi/cli/cmd_validate.py
dandi/pynwb_utils.py
dandi/validate.py

Add --devel-debug to `dandi validate`

---

dandi/cli/cmd_digest.py
dandi/cli/command.py
dandi/cli/tests/test_digest.py

Add "digest" command

---

dandi/tests/test_metadata.py

Don't hardcode DANDI_SCHEMA_VERSION value in tests

---

dandi/dandiapi.py

Check for already-uploaded blobs via /uploads/initialize/ instead of /blobs/digest/

---

dandi/model_types.py
dandi/tests/test_models.py

Lowercase "sha256"

---

dandi/cli/cmd_upload.py
dandi/core/digests/dandietag.py
dandi/dandiapi.py
dandi/upload.py

Upload file parts in parallel

---

dandi/cli/cmd_delete.py
dandi/cli/cmd_ls.py
dandi/cli/command.py
dandi/dandiapi.py
dandi/delete.py
dandi/tests/data/dandiarchive-docker/docker-compose.yml
dandi/tests/fixtures.py
dandi/tests/test_dandiapi.py
dandi/tests/test_delete.py
dandi/tests/test_upload.py
dandi/utils.py

Add "delete" command

---

dandi/dandiapi.py
dandi/girder.py
dandi/utils.py
setup.cfg

Retry requests that fail with 503

---

dandi/dandiapi.py
dandi/utils.py

Fix retrying 503's

---

dandi/dandiarchive.py
dandi/tests/test_dandiarchive.py

Support parsing & navigating asset download URLs

---

dandi/dandiarchive.py

This should fix the CLI for https://github.com/dandi/dandi-api/pull/219

Update dandiarchive client to use most_recent_published_version

---

dandi/upload.py

Log errors in extracting metadata for upload

---

dandi/cli/command.py

Log dandi, hdmf, h5py, and pynwb versions to log file

---

dandi/dandiarchive.py
dandi/tests/test_dandiarchive.py

Support "…/assets/?path=<path>" URLs

---

dandi/download.py

Refresh dandiset.yaml on download if out of date

---

dandi/tests/test_utils.py

Closes #569.
Note that #565 must be merged before the redirector is updated to point solely to dandi-api or else the `test_get_instance_actual_dandi` test will fail.

Add further tests of get_instance() and server-info

---

dandi/cli/cmd_validate.py
dandi/pynwb_utils.py
dandi/validate.py

Log validation errors

---

.pre-commit-config.yaml
CHANGELOG.md
dandi/cli/base.py
dandi/cli/cmd_organize.py
dandi/download.py
dandi/models.py
dandi/tests/fixtures.py
dandi/tests/test_utils.py
dandi/utils.py
setup.cfg
tox.ini

Add codespell

---

dandi/dandiapi.py

Closes #584.
(The failing tests are because https://dandiarchive.org is currently down.)

Retry upload requests that result in 500 responses

---

dandi/utils.py

Recognize "DANDI:<identifier>" strings as URL-likes

---

dandi/cli/cmd_ls.py
dandi/dandiarchive.py

Include list of supported URL patterns in `dandi ls --help`

---

dandi/dandiarchive.py
dandi/tests/test_dandiarchive.py

Make the "#/" in GUI URLs optional

---

dandi/dandiarchive.py
dandi/tests/test_dandiarchive.py

Allow trailing slash in GUI URLs

---

dandi/cli/cmd_shell_completion.py
dandi/cli/command.py
dandi/cli/tests/test_shell_completion.py
setup.cfg

Add "shell-completion" command

---

.autorc

As instructed [here](https://github.com/dandi/dandischema/pull/17#discussion_r640013204).

Set `auto` author to "DANDI Bot"

---

dandi/cli/cmd_download.py
dandi/cli/tests/test_download.py
dandi/download.py

Change `download --existing` default to "error"; add "overwrite-different" option; handle git-annex repos

---

dandi/cli/cmd_ls.py
dandi/cli/formatter.py
dandi/cli/tests/test_formatter.py
dandi/cli/tests/test_ls.py

dandi ls: Make json and json_pp formats output arrays; add json_lines for old json format

---

dandi/dandiapi.py
dandi/tests/test_dandiapi.py

Reprompt or fail on attempt to use an invalid API token

---

dandi/cli/cmd_ls.py
dandi/dandiapi.py
dandi/dandiarchive.py
dandi/delete.py
dandi/download.py
dandi/tests/fixtures.py
dandi/tests/test_dandiapi.py
dandi/tests/test_download.py
dandi/tests/test_upload.py
dandi/upload.py

Closes #673 (default to `dandi` instance)

Python API rewrite, part 1

---

dandi/dandiapi.py
dandi/tests/test_dandiapi.py

Closes #674.
I made this a method because, for most instances, it'll make an API request.

Add RemoteAsset.get_content_url() method

---

dandi/upload.py

Don't pass "asset" field from upload iterator to pyout

---

dandi/cli/cmd_upload.py
dandi/delete.py
dandi/tests/test_delete.py
dandi/upload.py

The command was removed when the Girder code was removed.

Remove references to "dandi register" command

---

dandi/metadata.py
dandi/tests/data/metadata/metadata2asset.json

changes of `unitText` in `extract_age`
a subset of changes from #450

changing unitText

---

dandi/dandiapi.py
dandi/metadata.py
dandi/tests/data/dandiarchive-docker/docker-compose.yml
dandi/tests/fixtures.py
dandi/tests/test_dandiapi.py
dandi/tests/test_utils.py
dandi/utils.py

Create valid Dandiset metadata when testing; create valid asset metadata for non-NWB files; wait for validation before publishing

---

dandi/dandiapi.py
dandi/tests/test_dandiapi.py

Adjust RemoteAsset.json_dict()

---

dandi/tests/test_metadata.py

While at it, I RFed the code to avoid duplicate logic for
two nearly identical tests
Not sure if that is the best way to proceed ATM, but should get tests into green again even when schema-0.5.0 gets released
Closes #704

BF+RF(TST): populate contentUrl to satisfy Asset requirement in 0.5.0

---

dandi/dandiapi.py
dandi/dandiarchive.py
dandi/delete.py
dandi/upload.py

Rename get_assets_under_path() to get_assets_with_path_prefix()

---

.github/workflows/test.yml

Test against rc/2.0.0 branch of pynwb

---

dandi/tests/test_download.py
tox.ini

Split off from https://github.com/dandi/dandi-cli/pull/775

Fix a test

---

dandi/cli/tests/test_ls.py
dandi/tests/fixtures.py
dandi/tests/skip.py
dandi/tests/test_dandiapi.py
dandi/tests/test_dandiarchive.py
dandi/tests/test_download.py
dandi/tests/test_utils.py
tox.ini

Apply "skipif_no_network" to all relevant tests

---

dandi/download.py
dandi/tests/test_download.py

Based on my reading of the code, there are only two points at which a suddenly-missing asset could cause a 404 while downloading:
* [At the call to `get_raw_metadata()`](https://github.com/dandi/dandi-cli/blob/902f7fdb6b7816dbc9c5a4a806628550702a1fcb/dandi/download.py#L199) when first starting to process an asset; this is the case that this PR addresses.  A 404 here is not as unlikely as you might think at first, as assets are fetched from the API in pages of 25 each, so there could be an arbitrary delay between an asset being initially fetched from the API and its metadata being fetched.
* [When actually performing the download](https://github.com/dandi/dandi-cli/blob/902f7fdb6b7816dbc9c5a4a806628550702a1fcb/dandi/download.py#L549); a 404 at this point already causes the download to stop …

Convert metadata 404's when downloading into an "error" status

---

dandi/tests/data/dandiarchive-docker/docker-compose.yml

Required for tests to pass for https://github.com/dandi/dandi-api/pull/640

Add DJANGO_DANDI_DANDISETS_EMBARGO_BUCKET_NAME setting to test docker-compose.yml

---

dandi/consts.py
dandi/dandiapi.py
dandi/tests/test_dandiapi.py

Added in https://github.com/dandi/dandi-api/pull/643
@jwodder should I merge this before or after I merge the change in dandi-api?

Add `embargo_status` to dandiset endpoint

---

dandi/metadata.py
dandi/tests/data/metadata/metadata2asset.json
dandi/tests/data/metadata/metadata2asset_3.json
dandi/tests/test_metadata.py

This adds ability to the CLI to resolve NCBITaxon urls and infer names of species from them. It also changes the way the name field is populated.

ENH: update species interpretation from NWB file

---

dandi/metadata.py
dandi/tests/data/metadata/metadata2asset_3.json
dandi/tests/test_metadata.py

also merges in #864 and closes #864

species url is case sensitive

---

dandi/cli/cmd_digest.py
dandi/cli/tests/test_digest.py
dandi/support/digests.py
docs/source/cmdline/digest.rst

Add zarr-checksum method to `dandi digest`

---

dandi/dandiapi.py

It was unclear to me what value I should use to use the staging instance. I propose this improvement to the init docstring
fix #889

improve DandiApiClient.__init__ docstring

---

dandi/cli/cmd_upload.py
dandi/upload.py
docs/source/cmdline/upload.rst

dandi upload: Make `--jobs` default to `5:5` and document it

---

dandi/dandiapi.py
dandi/files.py

Blocked by https://github.com/dandi/dandi-archive/pull/960.
Closes #937.

Trigger Zarr ingestion after performing an upload

---

dandi/tests/data/dandiarchive-docker/docker-compose.yml

Needed for https://github.com/dandi/dandi-archive/pull/1018

Add DANDI_JUPYTERHUB_URL to test docker-compose

---

dandi/tests/test_dandiapi.py

Part of #946.
This reduces the runtime of the test from 14.49s to 9.82s.

Combine subtests of `test_publish_and_manipulate`

---

dandi/bids_validator_xs.py

Closes: https://github.com/dandi/dandi-cli/issues/990

Setting version to min version if not available

---

dandi/metadata.py

@yarikoptic the issue @jwodder picked up on. I'm pretty sure this was a trace from the previous “autodetection” approach. Best see if purging it has unintended test consequences first. Thanks :)

Removing trace from previous commit

---

.github/workflows/test.yml
dandi/dandiapi.py
dandi/tests/test_dandiapi.py
dandi/tests/test_utils.py
dandi/utils.py
tox.ini

Closes #1019.
See https://github.com/dandi/dandi-cli/issues/1019#issuecomment-1139666971 for concerns about the runtime of the test.

Fetch paginated results concurrently

---

.codespellignore
dandi/download.py
dandi/tests/test_download.py
setup.cfg

Fix calculation of download paths for asset path prefix URLs

---

dandi/files.py
dandi/tests/test_upload.py

Reuse "loose" Zarrs that conflict with uploaded path

---

dandi/dandiapi.py
dandi/tests/test_dandiapi.py

Add `get_assets_by_glob()`

---

dandi/dandiarchive.py

Mention in help text that 'draft' is not supported in DANDI:<dandiset>/<version>

---

dandi/cli/cmd_move.py
docs/source/cmdline/move.rst

Add examples to `dandi move` docs

---

dandi/tests/fixtures.py

Update video NWB fixtures for next pynwb version

---

.github/workflows/test.yml

Test against dev version of keyring package

---

dandi/tests/fixtures.py

Pull latest Docker images before spinning up Compose

---

dandi/cli/cmd_ls.py

Make `dandi ls` properly detect embargoed Dandisets

---

DEVELOPMENT.md
setup.cfg

- adding testing instruction to `DEVELOPMENT.md`

adding testing instructions

---

.pre-commit-config.yaml

See https://github.com/PyCQA/isort/issues/2077 for more detail

boost isort in precommit to 5.12.0 to overcome issue with poetry

---

dandi/tests/test_files.py
setup.cfg

As per https://github.com/hdmf-dev/hdmf/pull/820

We no longer need to catch warning as hdmf has fixed the bug

---

dandi/exceptions.py
dandi/tests/test_upload.py
dandi/upload.py

Improve messages displayed when an upload fails

---

.github/workflows/test.yml
tox.ini

This reverts part of #315, as I believe the underlying issue has since been resolved.

Restore testing against Windows with Python 3.10

---

dandi/files/zarr.py

Blocked by https://github.com/dandi/dandi-archive/pull/1497.

Update for fix to Zarr upload procedure

---

dandi/metadata.py
dandi/tests/data/metadata/metadata2asset_3.json
dandi/tests/test_metadata.py

Metadata: add extraction of strain from nwb files

---

dandi/cli/command.py

Filter out pyout logs from logfile by default

---

.github/workflows/test.yml
dandi/tests/test_metadata.py
setup.cfg
tox.ini

Fix tests: avoid obolibrary (for now) and pynwb 2.3.0 (forever)

---

dandi/utils.py

Don't even test for `cp --reflink` support on Windows

---

README.md

Sadly only one as per https://repology.org/projects/?search=dandi
@yarikoptic may or may not be interested to also add it to (neuro) Debian. This might also motivate other maintainers to pick up the package.

Added distribution badge (sadly only one ATM)

---

dandi/download.py

Inform user with a warning in case of jobs > 1 but non pyout format

---

dandi/cli/cmd_validate.py
dandi/cli/tests/test_cmd_validate.py
dandi/tests/test_download.py
dandi/validate_types.py
docs/source/cmdline/validate.rst

Closes #1232.
I also cleaned up some of the code in `validate.py` because I couldn't stop myself.

Add `--ignore ID_REGEX` option to `dandi validate`

---

dandi/cli/cmd_service_scripts.py
dandi/cli/command.py
dandi/cli/tests/test_service_scripts.py
dandi/tests/fixtures.py
dandi/tests/test_metadata.py
dandi/tests/test_upload.py
docs/source/cmdline/service-scripts.rst

Add service script for re-extracting remote NWB metadata

---

dandi/cli/tests/test_command.py
dandi/files/bases.py
dandi/tests/test_files.py
dandi/tests/test_validate.py
dandi/validate.py

`validate`: Yield error if path is not inside a Dandiset

---

dandi/cli/cmd_validate.py
dandi/cli/tests/test_cmd_validate.py
dandi/tests/fixtures.py

Do not review yet, this is just a rough draft, needs [clarification upstream](https://github.com/NeurodataWithoutBorders/nwbinspector/issues/345) before anything interesting happens here:

Creating test for file-wise NWB error output listing

---

dandi/consts.py
dandi/dandiapi.py
dandi/tests/test_dandiapi.py

ref: https://github.com/dandi/dandi-cli/issues/1257

Log more information about retried HTTP requests

---

dandi/metadata.py

Add the ability for Subject.sex to be "O", indicating "Other" sex.

Accept Other sex as o abbreviation

---

dandi/tests/data/dandiarchive-docker/docker-compose.yml

Prereq for https://github.com/dandi/dandi-archive/pull/1570. After this is merged it will need a release to pass the full `dandi-archive` test suite.
pinging @jwodder @yarikoptic since I'm unable to use the request reviewers feature.

Add configuration for log buckets in testing

---

dandi/cli/cmd_download.py
dandi/cli/tests/test_download.py
dandi/dandiarchive.py
dandi/download.py
dandi/tests/fixtures.py
dandi/tests/test_dandiarchive.py
dandi/tests/test_download.py
docs/source/cmdline/download.rst
docs/source/ref/urls.rst

Support asset path globs in `dandi download`

---

dandi/cli/cmd_ls.py
dandi/dandiset.py
dandi/files/bases.py
dandi/tests/test_upload.py
dandi/tests/test_utils.py
dandi/upload.py
dandi/utils.py

Support uploading a subset of files from a BIDS dataset

---

dandi/cli/cmd_instances.py
dandi/support/typing.py
dandi/utils.py

Remove Python 3.7-specific code

---

dandi/tests/test_files.py

Fix test for newer hdf5

---

dandi/__init__.py
docs/source/conf.py

PR is primarily to test current state of CI given number of fails here and there.

Minor documentation tune up

---

CHANGELOG.md

Thank you codespell for finding a bug to submit a PR (ref: #1388)

Minor codespell fix in a CHANGELOG entry 

---

setup.cfg

PR to fix submitted https://github.com/NeurodataWithoutBorders/nwbinspector/pull/433
Closes #1400

Blacklist buggy nwbinspector 0.4.32

---

.pre-commit-config.yaml
dandi/files/bases.py
dandi/files/zarr.py
dandi/support/pyout.py
dandi/upload.py

Report progress in deleting Zarr entries during upload

---

.github/workflows/test.yml

Fix spelling of `--scheduled` option used in scheduled tests

---

.github/workflows/test.yml
dandi/tests/data/dandiarchive-docker/docker-compose.yml
dandi/tests/fixtures.py
dandi/tests/skip.py

Assorted Docker Compose improvements

---

setup.cfg

Blocked by https://github.com/dandi/dandi-archive/pull/2132

Support dandischema v0.11.0

---

dandi/download.py

Reduce looping & memory usage in ProgressCombiner

---

dandi/consts.py
dandi/dandiapi.py

Attempting to fix #1662 
applied to post & put since `iter_uploads` relies on both

Move retry status to uploads only

---

.autorc
.github/workflows/release.yml

@yarikoptic 
From https://github.com/intuit/auto/issues/2377

Fix auto release
