dandi/dandi-cli

dandi/tests/test_pynwb_utils.py
Unfortunately test is still not passing, I am no longer certain with what version of pynwb/hdmf tandem I saw the test pass (besides the tzinfo), but when I use older one I see only `None` values. And with current `dev` of pynwb and hdmf I see that it loads some fields as "tuples":
```
(git)hopa:~/proj/dandi/dandi-cli[enh-ls]git
$> python -m pytest -s -vv dandi/tests/test_pynwb_utils.py
==================================================================== test session starts =====================================================================
platform linux -- Python 3.7.3rc1, pytest-3.10.1, py-1.7.0, pluggy-0.8.0 -- /home/yoh/proj/dandi/dandi-cli/venvs/dev3/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/yoh/proj/dandi/dandi- …
```
=> RF: use explicit example  datetime with tzinfo set to tzutc()

dandi/cli/command.py, dandi/pynwb_utils.py
Commit comment in 1fd302325803f442162e3757414b5fc90ac1d502 summarizes situation with nwb_version a bit:
ENH: obtain also "nwb_version", ls it as NWB field in the table
I went for a shorter name in  ls  command since space is scarse.
Unfortunately I could not immediately figure out how to even populate
that field e.g. using NWBFile.  And PyNWB does not populate it
either ATM: https://github.com/NeurodataWithoutBorders/pynwb/issues/1085
The only example I found quickly with nwb_version field populated was from
///crcns/ssc-7 dataset -- and in particular
data/L4E_whole_cell/Exp_2015-09-05_001_0001-0162.nwb
file there.
I really think we should come up with some good, and not that large collection
of sample .nwb files to test on.  Unfortunately any "real" .nwb file seems to be
quite large …
=> ENH: ls - list NWB (version), lab, subject_id  where available; ignore warnings upon validate

dandi/cli/command.py, dandi/support/pyout.py
This PR reworks gh-11 and avoids the stalling issue mentioned there.  There's improvements that should be made on pyout's end, but what's here will work with the current release.
I've tested this out on the dandi/najafi-2018-nwb repo with
$ dandi ls data/FN_dataSharing/nwb/mouse1_fni16_15081{7,8}*.nwb
=> ls: Gather get_metadata() information asynchronously

.github/workflows/test.yml, .gitignore, dandi/__init__.py, dandi/cli/command.py, dandi/cli/formatter.py, dandi/cli/tests/test_command.py, dandi/cli/tests/test_ls.py, dandi/consts.py, dandi/pynwb_utils.py, setup.cfg
https://github.com/pyout/pyout/pull/86 is to add ability to hide columns which had no value in any of the rows.  This way we could aim to display the pertinent extended list of columns/metadata for the files at hand.
Overall - it works! formatting is a bit off, will report in pyout PR
By mistake pushed here also `--format` (Closes #25), and decided to just let it be here.  Unless there would be a need, let's proceed with changes "in bulk"
TODOs:
=> ENH: ls - hide empty columns; --format to choose output format

dandi/cli/command.py, dandi/consts.py, dandi/pynwb_utils.py
It allows for quite quite useful overview of what files actually contain:
(git-annex)lena:…proj/dandi/nwb-datasets/visual-coding-neuropixels/ecephys-cache[master]git
$> dandi ls session_71*/*nwb
PATH                                      SIZE    NWB  ND_TYPES
session_715093703/probe_810755797_lfp.nwb 2.1 GB  2.0b Device (2), DynamicTable, EcephysProbe, ElectricalSeries (3), LFP, ProcessingModule, TimeSeries
session_715093703/probe_810755799_lfp.nwb 2.5 GB  2.0b Device (2), DynamicTable, EcephysProbe, ElectricalSeries (3), LFP, ProcessingModule, TimeSeries
session_715093703/probe_810755801_lfp.nwb 2.2 GB  2.0b Device (2), DynamicTable, EcephysProbe, ElectricalSeries (3), LFP, ProcessingModule, TimeSeries
session_715093703/probe_810755803_lfp.nwb 2.3 GB  2.0b Device (2), DynamicTable, …
=> ENH: add nd_types (for neural data types) into "ls"

dandi/pynwb_utils.py, setup.cfg
… when encountering exception with AIBS_ecephys listed missing
Ultimate solution should IMHO be implemented within PyNWB itself.
See https://github.com/NeurodataWithoutBorders/pynwb/issues/1143 feature request.
Also related - dedicated exception (https://github.com/NeurodataWithoutBorders/pynwb/issues/1144)
With this change we should be able to deal with neuropixels files from Allen
=> ENH: autoimport allensdk.brain_observatory.ecephys.nwb

.github/workflows/test.yml
For that to work, we need to provide a secret token and that one would be available only (according to docs) if pull request comes from this repo (so cannot do from my fork... although may be I could set it there as well???)
=> ENH: upload coverage reports to codecov

dandi/cli/cmd_organize.py, dandi/exceptions.py, dandi/metadata.py, dandi/organize.py, dandi/pynwb_utils.py, dandi/tests/fixtures.py, dandi/tests/test_organize.py
The need for this was reminded by @satra and implementation uses proposed by him shorter version based on alphanum encoding of the crc32 checksum value, instead of the one I thought about -- first octet of object_id uuid (such change was done in 2845eda4c2fac4341c085d69debfc25e0a65ad94, which also has a brief show case example).
It could be seen needed on an older version of Kriegstein data (now no longer avail in dandiarchive)
- Diff is a bit big since in the first commit (362d346b069c15ca3d542b4b19b7fd3509bb647f ATM) I just refactored code by moving around to prepare for the follow up changes.
- I dropped "special" to "simulate" mode support for non-unique files handling - no need really.
TODOs:
=> ENH: organize - resolve ambiguity by adding _obj- where necessary

dandi/dandiset.py, dandi/download.py, dandi/utils.py
Info : https://github.com/yaml/pyyaml/pull/256
Closes #58
=> BF: consistent yaml (default_flow_style=False)

README.md, dandi/cli/cmd_download.py, dandi/download.py, dandi/girder.py, dandi/tests/skip.py, dandi/tests/test_download.py
- no support to download selected folders and files (well -- we cannot even do that anywhere among drafts AFAIK since we have only either folders or files ATM in a directory)
- comes with a basic unittest and drags along machinery from reproman for flexible and concise annotation of the tests to be skipped.
=> ENH: dandi download (multiple) files

setup.cfg
We have an additional entry below conditioned on py < 3.7
Let's see if tests pass
=> AFAIK no dateutil is needed for newer pythons.

dandi/support/tests/test_cache.py
The test kept flaking out on CI
>       assert len(calls) == ncalls + 1 + int(expect_new)
E       assert 3 == 4
E         +3
E         -4
which I attribute to the shared systems being slowish and possibly
susaining longer IO times.
=> BF(TST): do not fail test if indeed it took longer than _min_dtime

.github/workflows/test.yml
Filed issue against etelemetry-client to automate that:
https://github.com/sensein/etelemetry-client/issues/17
@satra, may be we would like to prune our records on etelemetry server after this is merged.
=> BF: export NO_ET=1 on github workflow - we must not artifiially blow up user counts

dandi/pynwb_utils.py, dandi/tests/test_pynwb_utils.py, setup.cfg
As reported on slack, we have use cases with nwb_version somehow `NWB-2.2.0`.
This PR strips NWB- prefix while obtaining the version, and would complain if that is to be happen for files with nwb_version >= 2.1.0 (in a custom comparison, so we defer to proper semver check later). 
`validate` also would now check and report a problem.  This is hopefully a temporary implementation within dandi -- hopefully nwb_schema would introduce constraints via regular expressions so validity of nwb_version could be checked "natively" by pynwb, see https://github.com/NeurodataWithoutBorders/nwb-schema/issues/426
There is no test for `validate` changes here.  I am (slowly) working on a separate branch to RF validation, so they will (hopefully) come there ;)
=> ENH: sanitize, validate and tolerate better wrong nwb_version

dandi/cli/tests/test_command.py
Not yet sure why but it can lead to stalling, most likely because
shell might be spitting out some errors so with PIPEs for both stdout,
stderr we get into the stalling of the process.
I kept running into the stall locally and now while building dandi conda package
=> BF: do not use shell=True to invoke test command

dandi/__init__.py, dandi/cli/tests/test_command.py
ATM conda has only 0.1.2 .  That one has no check_available_version.
This and other changes might come to etelemetry in the future and I do not
want to chase it.
=> RF: allow dandi to be used with outdated etelemetry

dandi/support/tests/test_cache.py
For some reason building for conda-forge on linux and osx resulted in that
test failures for not entire clear reasons... and then windows...  
Also now
- it will print those outputs so we possibly could troubleshoot,
- skip if we see what we saw on conda - running out of filename length.
- do not bother with full path in output - back slashes on windows confuse
poor python
Reference: https://github.com/conda-forge/staged-recipes/pull/11289  where it is included until a new dandi-cli release comes out (may be later today ;))
=> RF: refactor test to create dedicated script to run

dandi/download.py, dandi/exceptions.py, dandi/girder.py, dandi/tests/test_download.py
Closes gh-92 :
- supports download from netlify instance (going to the main girder)
- supports /v1/.../download girder urls
Also later added
- retry download up to 3 times (Closes gh-87)
Individual commit messages could provide more details
=> BF+RF: download - use regexes to prescribe known urls, support items and netlify

dandi/download.py
Ref #99 where @satra wants to go even more wild and handle all redirects - yet to see a support for that.
As for identifiers Seems to work (no dedicated unittest):
$> dandi download https://identifiers.org/DANDI:000004
2020-05-12 12:07:53,034 [    INFO] Downloading folder with id ['5e6ff4140fe0ec33e6b3d5d2'] from https://girder.dandiarchive.org/
2020-05-12 12:07:54,819 [    INFO] Traversing remote dandisets (000004) recursively and downloading them locally
2020-05-12 12:07:54,819 [    INFO] Updating dandiset.yaml from obtained dandiset metadata
sub-P15HMH_ses-20070901_obj-8et7lc.nwb:  19%|███████▍                               | 10.4M/54.7M [00:22<04:35, 161kB/s^Cub-P10HM_ses-20060901.nwb:  29%|██████████████▊                                    | 21.2M/73.2M [00:21<02:55, 296kB/s] …
=> BF: explicit request to handle redirect for identifiers.org

dandi/cli/cmd_upload.py, dandi/consts.py, dandi/download.py, dandi/girder.py, dandi/support/digests.py, dandi/support/tests/test_digests.py, dandi/utils.py
3 right away to capture popular checksums which could possibly later help to identify this file in other places (e.g. datalad uses md5 by default, git annex - sha256, and sha1 iirc used by git)
Theoretically we could provide some progress indication while computing digests which would be valuable for large files, but IMHO not a priority
Unfortunately there is still no unittests for upload, so nothing is tested beyond local tries.
@satra - please recommend another name than `uploaded_digests` for the metadata field.  I kept `uploaded_` prefix consistent with other metadata fields I add upon upload.
TODOs
- (later, possibly) extend with digests for s3 digest with our blocking setting, default ipfs
Closes gh-106
=> ENH: Upload digests (only 4 checksums for now)

dandi/consts.py, dandi/organize.py, dandi/pynwb_utils.py, dandi/tests/test_organize.py
Apparently we had no issue open for support disambiguation with a sample case of https://dandiarchive.org/dandiset/000022 .
It also "fixes" obviously wrong
```python
mandatory_if_not_empty=["modalities,"]
```
which I am not yet 100% sure how played its evil roles since awhile.
TODOs:
=> RF+ENH: support using probe_id to disambiguate (before obj_id)

dandi/cli/cmd_upload.py
commit 808e5894af0c4b613d13fbba444a03a1ff97164b (HEAD -> upload-all, origin/upload-all)
NF: upload - --allow-any-path development option
Coupled with  --validation ignore  it would allow upload of any file (not only .nwb,
and dandiset.yaml).  Metadata record for any non .nwb file would be pretty much empty
ATM BUT it will contain the digests (checksums ATM), thus allowing to verify downloads etc.
Note -- it is a "development" option, so will not be visible/available by default.
Informed users would need to set DANDI_DEVEL=1 environment variable first.
=> BF+ENH: allow for upload of any file (but not that easily for now)

README.md, dandi/cli/command.py
Now it would look like
```
$> dandi --help
Usage: dandi [OPTIONS] COMMAND [ARGS]...
A client to support interactions with DANDI archive
(http://dandiarchive.org).
To see help for a specific command, run
dandi COMMAND --help
e.g. dandi upload --help
Options:
--version
-l, --log-level [DEBUG|INFO|WARNING|ERROR|CRITICAL]
Log level name  [default: INFO]
--pdb                           Fall into pdb if errors out
--help                          Show this message and exit.
Commands:
download  Download a file or entire folder from DANDI
ls        List .nwb files and dandisets metadata.
organize  (Re)organize files according to the metadata.
register  Register a new dandiset in the DANDI archive
upload    Upload dandiset (files) to DANDI archive.
validate  Validate files for NWB (and DANDI) …
```
=> DOC: inform that there is dandi COMMAND --help

dandi/cli/cmd_upload.py
I should have done it before 0.5.0 ;-)
=> ENH: add uploaded_by field which would inform what version of dandi client uploaded it

doc/demos/basic-workflow1.sh
There's still an error with `sed` in the `basic_workflow1.sh` script that I don't know how to fix.  If I remove the indent step in sneak the script runs.
=> make mktemp compatible with MacOS and linux

dandi/cli/cmd_upload.py
otherwise we try to remove paths which might have had leading ./ which causes
exception upon attempt to remove it, as has been reported by a user:
bash-4.2$ DANDI_DEVEL=1 dandi upload --allow-any-path --validation ignore ./rawdata/sub-I46/ses-MRI/anat/test.json
Please enter password for encrypted keyring:
2020-07-20 17:23:23,255 [    INFO] Found 1 files to consider
PATH                                   SIZE         ERRORS     UPLOAD      STATUS                       MESSAGE
rawdata/sub-I46/ses-MRI/anat/test.json 196 Bytes       2       100%        done
Summary:                               196 Bytes 1 with errors 95 Bytes/s  1 done
ERROR: 1 asynchronous worker failed
Producing value for row ('rawdata/sub-I46/ses-MRI/anat/test.json',) failed:
Traceback (most recent call last):
File …
=> BF: Place into process_paths "normalized" (via Path) paths

MANIFEST.in, setup.py
This is the simplest possible change to make it possible to build the project with PEP 517 (e.g., using pip or tox).  Without this change, `versioneer.py` is unimportable during the build.  See warner/python-versioneer#193, warner/python-versioneer#192, and pypa/pip#6163 for more information.
This PR also adds `versioneer.py` to `MANIFEST.in` so that it will be present in sdists, which is necessary for wheels built from an sdist to have the correct version set in their metadata.
=> Make it possible to build package via PEP 517

dandi/cli/cmd_organize.py, dandi/utils.py
`'\.'` is not a valid escape sequence in Python strings, and so it generates a SyntaxError under Python 3.8.3.
=> Convert regexes with invalid escapes to raw strings

dandi/cli/cmd_register.py
Without this patch, `dandi --help` lists the following description for `register`:
Register a new dandiset in the DANDI archive This command...
=> Add a period to the end of the first line in register's docstring

pyproject.toml, setup.cfg, setup.py
download_url (which seems to be effectively deprecated anyway) is not the appropriate place to put a repository URL.
This requires setuptools 38.3.0+.
=> List repository URL in project_urls

.gitignore, setup.cfg, tox.ini
`setup.py test` and `tests_require` are deprecated [[1]](https://setuptools.readthedocs.io/en/latest/setuptools.html#test-build-package-and-run-a-unittest-suite) [[2]](https://github.com/pypa/setuptools/issues/1684), with `tox` or similar recommended instead.
=> Set up testing with tox

dandi/tests/fixtures.py
Without this change, pynwb generates the warning "UserWarning: Date is missing timezone information. Updating to local timezone."
=> Fix warning caused by lack of tzinfo

tox.ini
This makes flake8 ignore anything outside the `dandi` directory (such as `venv/`) without having to constantly add to flake8's exclusions list.
=> Restrict flake8 to dandi directory

tox.ini
Warnings generated by pynwb due to `load_namespaces=True` are ignored.
This PR includes the changes from #144.
=> Configure pytest to fail on warnings

dandi/tests/test_download.py
ref #111, which will be closed by #134
=> BF(workaround): skip test if download blows due to tqdm locking issue

dandi/cli/cmd_upload.py
Before it was used via imported binding within girder module, which
we recently flake8-ed away.  Since no "upload" tests, breakage went unnoticed
Thanks @alejoe91 for living on the bleeding edge and reporting back upon the first cut ;-)
=> BF: import known_instances directly

.github/workflows/test.yml
Failures to upload to codecov come and go.  AFAIK there is no way to
retry and thus we will just allow to skip if codecov "errors"
=> BF(workaround): do not fail test workflow if codecov fails

dandi/tests/fixtures.py, dandi/tests/test_register.py, dandi/tests/test_upload.py
Also define a `local_docker_compose_env` fixture that sets `DANDI_API_KEY`.
Closes #172.
=> Add "instance" and "instance_id" keys to local_docker_compose return value

.github/workflows/test.yml, dandi/girder.py, dandi/tests/test_download.py
This should also stabilize coverage reporting since tested code paths shouldn't vary
While at it
- added smoke testing of logging when `_DANDI_LOG_GIRDER` is set to a single run in the matrix
- added a test that our tqdm progress reporter does not blow when tqdm blows with assertion error
=> BF+ENH: workaround tqdm exception, test girder retries loop, ensure sleep of at least 1 sec

dandi/consts.py, dandi/tests/data/dandiarchive-docker/docker-compose.yml
Closes #170.
Before this PR can be accepted, dandi/redirector#16 needs to be merged, after which we can set up the redirector image on Docker Hub.
Also note that this PR uncomments the client container so that the redirector will have something to redirect to, even though the client container currently returns only blank pages due to the Girder container using a non-default port.  [I've asked dandi/dandiarchive to address this point, though.](https://github.com/dandi/dandiarchive/issues/468)
=> Add Dockerized redirector to Docker Compose

tox.ini
So that I can pass arguments to pytest from the tox command line.
=> Add {posargs} to pytest command in tox

dandi/cli/formatter.py, dandi/cli/tests/test_ls.py, dandi/dandiset.py, dandi/organize.py, dandi/tests/test_organize.py, dandi/tests/test_register.py, dandi/tests/test_upload.py, dandi/utils.py, dandi/validate.py, setup.cfg
There's no reason to use two YAML libraries, so this PR gets rid of the one that doesn't support round-tripping comments.
**Note**: dandi-cli currently uses the API introduced in ruamel.yaml 0.15.0 (featuring `ruamel.yaml.YAML()` and its `load()` and `dump()` methods, as opposed to using the `load()` and `dump()` functions directly in `ruamel.yaml`), and this PR does that as well.  However, [the ruamel.yaml docs](https://yaml.readthedocs.io/en/latest/basicuse.html) state that the new API is "still in the process of being fleshed out" and recommend that production software use pre-0.15 versions of the library.  Should we follow that advice?
=> Eliminate pyyaml dependency

dandi/tests/test_register.py
These became unused in commit 93b8cc2 but were not removed at the time.
=> Remove unused monkeypatches

dandi/conftest.py, dandi/support/tests/test_cache.py, dandi/support/tests/test_digests.py, dandi/tests/fixtures.py, dandi/tests/skip.py, dandi/tests/test_download.py, dandi/tests/test_organize.py, dandi/tests/test_utils.py, setup.cfg
There have been several times today and/or yesterday when linting of test files would have saved me some failed trips through the test suite.
=> Configure flake8 to run on test code as well

.github/workflows/test.yml, dandi/download.py, dandi/exceptions.py, dandi/register.py, dandi/tests/data/dandiarchive-docker/docker-compose.yml, dandi/tests/test_utils.py, dandi/upload.py, dandi/utils.py, setup.cfg, tox.ini
=> Add a get_instance() function

dandi/exceptions.py, dandi/girder.py, dandi/tests/test_girder.py, dandi/tests/test_upload.py, dandi/upload.py, setup.cfg
It locks the entire dandiset for the entire operation (loop across all
files), even if no actual upload would happen (e.g. if all files
already uploaded and recent).
It has a few TODO items added in the code which ideally should be
resolved before we proceed with merging this PR.
Closes #125 since ATM `upload` is the only one which modifies  an existing dandiset
=> ENH: upload - add locking of the dandiset

dandi/tests/test_download.py
no girder based urls any more.  
Hopefully that resolves our now failing tests.
=> BF(TST): redirector now directs to new web ui addresses for drafts of dandisets

dandi/cli/cmd_ls.py, dandi/cli/cmd_organize.py, dandi/tests/test_organize.py, dandi/utils.py
Without this change, find_dandi_files() would match files whose names ended with "dandiset.yaml" (e.g., "foodandiset.yaml").  I don't think that's intended.
Using `$` instead of `\Z` causes a regex to also accept strings that end with a newline.  That's not desirable here.
=> Fix some find_files() regexen

dandi/support/tests/test_cache.py
If I'm reading the report right, this was the only bit of code that lost coverage from #217.
Closes #218.
=> Don't test coverage of runtime-sensitive code

DEVELOPMENT.md, dandi/consts.py, dandi/tests/fixtures.py
On the host ATM I did
```
(git)lena:~/proj/dandi/dandi-cli[master]git
$> git diff
diff --git a/dandi/tests/data/dandiarchive-docker/docker-compose.yml b/dandi/tests/data/dandiarchive-docker/docker-compose.yml
index 5b825e2..2ce67d3 100644
--- a/dandi/tests/data/dandiarchive-docker/docker-compose.yml
+++ b/dandi/tests/data/dandiarchive-docker/docker-compose.yml
@@ -42,8 +42,8 @@ services:
ports:
- "8079:8080"
environment:
-      GIRDER_URL: http://localhost:8081
-      GUI_URL: http://localhost:8086
+      GIRDER_URL: http://192.168.1.34:8081
+      GUI_URL: http://192.168.1.34:8086
ABOUT_URL: http://www.dandiarchive.org
volumes:
diff --git a/dandi/tests/test_upload.py b/dandi/tests/test_upload.py
index e7a3163..1100695 100644
--- a/dandi/tests/test_upload.py
+++ …
```
=> 90% of way to enable testing from windows VM over to an instance running on the host

dandi/download.py, dandi/utils.py, setup.cfg
- datetime stamp now has zone `Z` suffix which breaks "stock" datetime.fromisoformat parsing -- use `datetutil` implementation
- metadata for dandiset now returned not within `dandiset` subkey of metadata record.
"Good" news -- no real released dandisets are out there yet, so no user should be impacted AFAIK.
=> BF: address for changes in returned by API records

.github/workflows/test.yml
This configures the "test" workflow to be run once a day at 6 AM UTC, presumably when no one is working on the code.
Closes #230.
=> Run GitHub Actions tests daily

dandi/cli/formatter.py
=> Make YAMLFormatter sort keys

dandi/cli/cmd_register.py, dandi/dandiset.py, dandi/download.py, dandi/girder.py, dandi/register.py, dandi/tests/test_register.py, dandi/tests/test_upload.py, dandi/upload.py
In #233 (post 0.6.4 release, current master) I have tried to unify metadata records, but did that incorrectly for dandisets. I forgot that those would also be used during `upload` which caused fiasco in uploading sample 000029 (web ui is also not tolerant to bad metadata)
As part of this PR I also
- adjuster `register` to always return record given by the server, and adjusted (and refactored a bit) corresponding test of register
- included test by @jwodder from #241 (Closes #240) and adjusted it to use `register`
- `dandiset.yaml` would no longer be uploaded at all to the archive.  we already add a comment that all changes are to be lost, so we should actually do that (i.e. not upload so all changes lost)
=> BF: dandiset metadata record structure/assumptions

.github/workflows/test.yml
The set-env workflow command is deprecated in favor of environment files: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Use environment file instead of set-env

dandi/girder.py
=> Use oldest file when race condition causes multiple files per item

.autorc, .github/workflows/release.yml, CHANGELOG.md, DEVELOPMENT.md
Addresses part of #252.
**Note:** I would recommend not merging this PR until after the next release of dandi-cli so that we can start fresh with labelling all of our PRs.
This PR also needs to be accompanied by the following changes:
=> Set up workflow with auto for releasing & PyPI uploads

dandi/girder.py, dandi/support/tests/test_ui.py, dandi/support/ui.py, dandi/tests/test_girder.py, setup.cfg
=> Make keyring lookup more flexible

README.md
To avoid maintaining two documentations, where each one coughs get out of sync.
Closes #278
=> DOC: strip away duplicate with the handbook information

dandi/__init__.py, dandi/due.py, setup.cfg
I am using Zenodo unversioned DOI
```shell
$> DUECREDIT_ENABLE=1 python -m pytest dandi/tests/test_utils.py
====================================================== test session starts ======================================================
platform linux -- Python 3.8.6, pytest-4.6.11, py-1.9.0, pluggy-0.13.0
rootdir: /home/yoh/proj/dandi/dandi-cli, inifile: tox.ini
plugins: mock-3.2.0, cov-2.10.0, pyfakefs-4.1.0, forked-1.3.0, timeout-1.4.1, xdist-1.32.0, hypothesis-5.32.1
collected 19 items                                                                                                              
dandi/tests/test_utils.py ...................                                                                             [100%]
=================================================== slowest 10 …
```
=> Add rudimentary duecredit support using zenodo's dandi-cli DOI

dandi/pynwb_utils.py
h5py 3.0 introduced breaking changes (see e.g. https://github.com/dandi/dandi-cli/issues/282)
and hdmf yet to account for them.  We better cache that version too to improve
consistency of outputs etc
=> BF: add h5py.__version__ into the list of tokens for caching

dandi/cli/cmd_ls.py, dandi/cli/formatter.py, dandi/pynwb_utils.py, setup.cfg
TODOs
Closes #282
oh well -- migrating away from ad-hoc limit to max_workers + wait_for_top of pyout does change UX since for long lists of files we would have only the top of the terminal "busy" while the bottom just with the filenames and sizes.  But I decided to stick with that for now, although may be I would whine to @kyleam later on or just reintroduce ad-hoc solution, or may be it would be somehow more natively resolved within dandi-cli upon RFing to use ProducerConsumer pattern outside of pyout.
=> ls - avoid workaround, more consistent reporting of errors

dandi/models.py, dandi/tests/test_models.py
This is something I've noticed for a while now, and figured I'd just add these titles. Almost all of the titles are just the variable name with capitalization and spaces, so I doubt there's much wrong here, but if there is please lmk.
=> Add title to `Field` calls where necessary

dandi/upload.py
See https://github.com/dandi/dandiarchive/issues/517 for more information
If looks kosher and doesn't break anything, we should get it into the masses, unless we find a proper solution to that issue.
we might want to announce all prior versions of dandi-cli as "bad" in .et
=> Temporary workaround: prevent upload of files larger than 67108864000

dandi/tests/test_organize.py
This was causing a `PytestUnraisableExceptionWarning` to be raised under pytest 6.2 and Python 3.8+.
=> Close a file in a test case

.github/workflows/test.yml
On December 9, hdmf released a new version that restricted its h5py dependency version range to `<3,>=2.9`; as a result, installing dandi with a recent version of pip will install a pre-3.0 version of h5py.  However, pre-3.0 versions of h5py do not have Python 3.9 wheels available on PyPI, and so the package must be built from source for Python 3.9, which requires an hdf5 library to be installed.  This PR installs such a library for Ubuntu and macOS when testing Python 3.9; testing Python 3.9 on Windows is disabled for now as installing hdf5 on that OS is apparently quite involved.
=> Install hdf5 for Python 3.9 tests

dandi/consts.py, dandi/dandiapi.py, dandi/tests/data/dandiarchive-docker/docker-compose.yml, dandi/tests/fixtures.py, dandi/tests/test_dandiapi.py
=> Update for new API at https://api.dandiarchive.org/api

dandi/cli/base.py, dandi/cli/command.py
Closes #316 
Unfortunately, if the program exits abnormally, the final message giving the location of the logfile won't be printed.  I'm not aware of a way around this.
=> Tee all logs to user log directory

CHANGELOG.md, dandi/metadata.py, dandi/models.py, dandi/tests/test_metadata.py, dandi/tests/test_validate.py
this is a draft PR to try and clean up the asset model. i haven't updated tests yet. putting the model changes here up for discussion.
=> cleaning up biosample and participant

dandi/tests/test_girder.py
On December 22, keyring released version 21.6, which no longer initializes keyring backends on import, instead delaying initialization until any functions are called.  As a result, when dandi-cli’s tests are run, the EncryptedKeyring backend is only initialized in the middle of individual tests, and these tests happen to use pyfakefs.  However, initializing EncryptedKeyring leads to a use of the subprocess module, which is unusable while pyfakefs is in effect, and the tests end up failing.
This PR forces the keyring backends to be initialized when the tests are loaded, before any of them run, thereby fixing the currently-failing tests.
The only thing I don’t understand is why this was only causing a problem on macOS.
=> Require keyring backends to be initialized before running any tests

dandi/models.py
See https://github.com/dandi/dandi-cli/issues/333 for more information/reasoning
=> [DATALAD RUNCMD] Swap order of str and AnyUrl to be from specific to generic

dandi/metadata.py, dandi/models.py, dandi/tests/test_metadata.py, dandi/tests/test_validate.py, setup.cfg, tools/pubschemata.py
=> Add functions for validating metadata against JSON Schema and use in tests

DEVELOPMENT.md, dandi/cli/cmd_download.py, dandi/consts.py, dandi/dandiapi.py, dandi/dandiarchive.py, dandi/dandiset.py, dandi/girder.py, dandi/tests/fixtures.py, dandi/tests/test_dandiapi.py, dandi/tests/test_dandiarchive.py, dandi/tests/test_download.py, dandi/tests/test_girder.py, dandi/tests/test_upload.py, dandi/tests/test_utils.py, dandi/upload.py, dandi/utils.py
Closes #320.
@yarikoptic This is still in progress, but I'd appreciate feedback on what I have so far.
TODOs:
- add support for downloading a specific folder (that was disabled)
- I [hardcoded](https://github.com/dandi/dandi-cli/pull/330/files#diff-b717531d4b8b009b048e5ffe354df41bb1d0ff779121156b42528d53227ddc7eR274) to consider "draft" to be the "latest version" .  We should remove that and allow for version to be left unspecified, and then `DandiAPIClient` code handle it properly (get the latest version, download for it)
- 
Moved two last items into a dedicated issue to follow up not here: https://github.com/dandi/dandi-cli/issues/340
=> Support CLI uploading & downloading via new API

dandi/cli/cmd_upload.py, dandi/dandiapi.py, dandi/dandiset.py, dandi/tests/test_upload.py, dandi/upload.py
Closes #339 
ref https://github.com/dandi/dandi-api/issues/66 on not forgetting the trailing `/`
TODO
=> ENH: devel upload dandiset metadata

dandi/upload.py
How that happened, nobody knows.  But since we are making judgement anyways
only on the metadata in the item, we will just allow to remove the entire item
and reupload that file
attn @CodyCBakerPhD
=> BF: allow to handle an item with multiple files

.github/workflows/test.yml
Fixes #352.
Fix inspired by [this comment](https://github.com/pypa/pip/issues/9542#issuecomment-770379808).
Unfortunately, I do not see a way to ensure that users of dandi-cli who do not already have numpy installed do not run into this problem.
=> Fix numpy dependency issue in tests

dandi/models.py, dandi/upload.py
Since it seems we're going to be doing this sort of conversion frequently, this PR adds a method to `CommonModel` for recursively converting to a `dict` while also converting enum values to strings.
=> Give AssetMeta and DandiMeta `json_dict()` methods for better dictification

.github/workflows/test-populate-dandiset-yaml.yml
=> Add workflow for running populate_dandiset_yaml.py

dandi/dandiapi.py, dandi/tests/test_dandiapi.py, dandi/tests/test_upload.py, dandi/upload.py
=> Handle uploading already-present files in new API

dandi/metadata.py
=> Discard invalid asset identifiers when extracting metadata

dandi/dandiapi.py, dandi/dandiarchive.py, dandi/tests/test_dandiapi.py
=> Add `include_metadata=False` parameter to asset-listing DandiAPIClient methods

DEVELOPMENT.md
These labels are not listed in auto's documentation, but they are still recognized & used, as can be seen by dumping a repository's auto config with `auto info -v`.
=> List extra auto labels in DEVELOPMENT.md

dandi/cli/cmd_validate.py, dandi/validate.py
=> Give `validate` command a `--schema VERSION` option for validating assets and dandiset.yaml

dandi/cli/cmd_download.py, dandi/cli/tests/test_download.py
Closes #153.
Note that the tests for this change must be run with `DANDI_DEVEL=1`, which also enables `test_enormous_upload_breaks_girder`.  As a result, the new tests are not run under CI.
=> Make `dandi download -i <instance>` run in a Dandiset download that Dandiset

dandi/metadata.py, dandi/models.py, dandi/tests/test_metadata.py, dandi/validate.py
Identifiable is a mix-in class for anything with an identifier.
It is "extracted" from the CommonModel since we might not have identifiers defined locally.
BareAssetMeta provides a base class to AssetMeta which could then be populated only on the server side.
This PR is more of an experiment as a possible solution to #369 .  In converted schema it should all still look the same (didn't check though), may be only for some reordering of keys within schema.
=> RF/NF: Identifiable and BareAssetMeta to describe an asset anywhere

dandi/dandiapi.py, dandi/upload.py
Currently, when uploading a file to the new API with the `upload()` function / `dandi upload` command, its digest is computed twice: once for use in the metadata and again for use in the validation API.  This PR lets DandiAPIClient's upload methods accept a precomputed digest so that we only need to digest each file once.
=> Support passing precomputed file digest to DandiAPIClient upload methods

dandi/tests/test_upload.py, dandi/upload.py
=> Make existing="refresh" a synonym for "overwrite" for new upload

dandi/dandiapi.py, dandi/support/digests.py, dandi/upload.py
Closes #389.
This PR reverts #388.
=> Cache file digests and check for change in digest when uploading

dandi/dandiapi.py
=> Sleep increasing amounts while waiting for uploaded assets to validate

dandi/tests/fixtures.py
To make debugging failed tests easier.
=> Capture all dandi log messages when testing

dandi/tests/test_dandiapi.py
=> Add test of upload of large file to new API

dandi/dandiapi.py, dandi/tests/test_dandiapi.py
See [this comment](https://github.com/dandi/dandi-cli/issues/414#issuecomment-784347724) and dchiquito's response
=> Revert PR #409 (Content-MD5 header)

dandi/cli/command.py, dandi/dandiapi.py
Closes #416.
Note that the process and thread ID are only included in the logs logged to the log directory.  Let me know if you want them included in the logs printed to the screen as well.
=> Log failed HTTP connections; include PID and TID in logs; include asset path in upload log messages

dandi/dandiapi.py, dandi/upload.py
This PR changes the names of the "validation" statuses when uploading to "pre-validation" (done client-side before uploading) and "post-validation" (done server-side after uploading) so that one can more accurately tell what state an upload is in.
=> Distinguish between pre- and post-validation when uploading

dandi/dandiapi.py
Due to too much copy & paste, dandi currently logs "Successfully authenticated using the key from the envvar" after setting the authentication token to the new API to a value obtained from the environment.  This is misleading, as no authentication step is actually performed or can be performed with the new API, and so this PR removes that message.  (If we wanted to, we could probably check token validity with a request to `/users/me/`, but that seems a little bit wasteful, especially considering the token can be expected to be used for actualy requests right after anyway.)
=> Remove misleading log message about authenticating with new API

dandi/dandiapi.py, dandi/utils.py
This PR sets a User-Agent header when communicating with the new API that contains the version of dandi in use.
=> Report dandi version in User-Agent header

dandi/__init__.py, dandi/dandiset.py, dandi/tests/test_organize.py, dandi/utils.py, setup.cfg, tox.ini
This is a collection of minor edits to the code that aren't really worth their own PRs.  See each commit for descriptions of the changes.
=> Assorted code cleanup

dandi/dandiapi.py
I believe that `iter_content()` is the preferred way to iterate over a streaming `requests.Response`.  Note that this comes with a slight change in behavior, as `iter_content()` calls `raw.stream()` with `decode_content=True`, which causes Content-Encodings to be decoded, which I believe is the correct thing to do.
=> Use iter_content() instead of raw.stream()

dandi/tests/data/dandiarchive-docker/docker-compose.yml
As of https://github.com/dandi/dandi-api/pull/83, the dandi-api Django setup requires the `DJANGO_DANDI_SCHEMA_VERSION` environment variable to be set in order to run; without it, our tests fail.
=> Set DJANGO_DANDI_SCHEMA_VERSION in docker-compose.yml

dandi/dandiapi.py
I've encountered `requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.dandiarchive.org', port=443): Pool is closed.` a couple times while testing uploads to the new API.  This PR should take care of that.
=> Retry requests on ConnectionErrors

dandi/metadata.py
I believe these are the only fields whose conversion functions need updating.
Closes #436.
=> Discard empty "sex" and "species" fields on conversion

.github/workflows/test-populate-dandiset-yaml.yml
=> Check out dandi/dandi-api-datasets with direct `git clone`

.autorc, .github/workflows/release.yml
This eliminates the use of `auto version` (a failure in which led to a failed & unsolicited attempt at uploading to PyPI) in favor of triggering the build & upload via auto's `exec` plugin and its `afterRelease` hook.
=> Simplify release workflow

dandi/models.py
This should address the change to using `Enum` for `Literal` in pydantic 1.8+. This reverts the schema generation to use `const`. This change can be reverted once https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/212 is addressed.
=> fix: change enum to const for single enums

dandi/dandiapi.py
Primarily was added to resolve the mystery of ETag of the file
from blob store not corresponding to precomputed one.  Which was
(as reported in detail in
https://github.com/dandi/dandi-api/pull/150#issuecomment-795456385
due to us then moving that blob from staging area into blob store
using different chunking logic, with smaller number of chunks
=> ENH: more of lgr.debug for multipart upload

dandi/cli/cmd_validate.py
=> Display `dandi validate` errors using logger

setup.cfg
May be some other release could be fine as well, but with 1.7.3
I do have tests erroring out with
(git)lena:~/proj/dandi/dandi-cli-master[master]git
$> python -m pytest -s -v dandi/tests/test_models.py::test_autogenerated_titles
============================================================================ test session starts ============================================================================
platform linux -- Python 3.9.1, pytest-6.2.2, py-1.9.0, pluggy-0.13.0 -- /home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/yoh/proj/dandi/dandi-cli-master/.hypothesis/examples')
rootdir: /home/yoh/proj/dandi/dandi-cli-master, configfile: tox.ini
plugins: mock-3.5.1, pyfakefs-4.1.0, …
=> BF: Require pydantic >= 1.8.1

dandi/__init__.py, dandi/cli/command.py
=> Only call logging.basicConfig() when used as a command

tools/s3-gc-stats
=> Script for generating S3 versioned file stats

README.md, dandi/core/__init__.py, dandi/core/digests/__init__.py, dandi/core/digests/dandietag.py, dandi/core/digests/tests/test_dandietag.py, dandi/support/digests.py
This is an initial interface which could be used to get a complete
digest for a file (serially ATM, but could be parallelized across parts),
just a list of part sizes, or be used iteratively to update a digest
e.g. during upload or download as more data comes in.
Closes #464 
TODOs
Later, after merge so could be used by dandi-api:
- use within `upload` and `download` for new dandi-api
- verify etag matching for some large files already uploaded to S3
=> ENH: prototype for the DANDIEtag "digester"

dandi/consts.py, dandi/model_types.py, dandi/models.py, dandi/tests/test_metadata.py, dandi/tests/test_models.py
See [here](https://github.com/dandi/dandi-cli/pull/479#discussion_r598897361) and related conversation.
Note that I changed the name of the enum from `dandi-etag` to `dandi_etag` so that it would be a valid Python identifier.
=> Add dandi_etag digest type to schema

dandi/upload.py
When uploading to the new API, when the code actually reaches the point at which the upload proper happens, a "CURRENT" column appears at the right side of the pyout display containing the current number of bytes uploaded per file.  As this column is not declared in the list passed to the pyout table constructor, I assume it is not supposed to be displayed in the first place.  This PR removes the "current" field from the upload progress dict before yielding it to pyout, which should get rid of the column.
=> Remove "current" column from upload progress display

dandi/cli/cmd_ls.py
=> dandi ls: Error if --schema is given with remote resource of different version

dandi/core/digests/dandietag.py, dandi/dandiapi.py, dandi/download.py, dandi/pynwb_utils.py, dandi/support/digests.py, dandi/tests/test_upload.py, dandi/upload.py
=> Update upload code for changes in API

dandi/upload.py
=> Validate uploads before digesting

.github/workflows/test.yml, dandi/conftest.py
Part of https://github.com/dandi/dandi-api/issues/42.
Note that this PR will need to be part of a release of dandi-cli before the dandi-api+dandi-cli integration tests can use the released version of dandi-cli.  If you are OK with releasing immediately, add the "release" tag to this PR before merging.
=> Add option for only running new Dandi API tests

tox.ini
A new version (0.17.0) of ruamel.yaml was released a few hours ago which added deprecation warnings to some top-level functions.  hdmf uses one of these functions, and so our tests were erroring out due to the warnings.  This PR ignores the warnings, and I've already filed [a bug report](https://github.com/hdmf-dev/hdmf/issues/547) with hdmf.
=> Ignore warnings from ruamel.yaml caused by hdmf using deprecated functions

dandi/consts.py, dandi/metadata.py, dandi/models.py
closes #503 
Current dandiset metadata conversion was generating invalid values for some properties (Person, Resources, etc.,.). This updates the migration code to address these issues.
Also the current assets metadata uses modality, which is being renamed to approach.
=> Fixes conversion of existing dandiset metadata with sub-object validation

dandi/tests/fixtures.py
This PR causes the Girder "provision" container to be run in the foreground when spinning up the Docker Compose setup.  This allows us to catch provisioning failures early and also causes the logs for the container to be displayed, allowing debugging.  Both are relevant to fixing the failures currently seen on https://github.com/dandi/dandi-api/pull/183.
In case you're wondering why a Girder container is being spun up for dandi-api tests: The dandi-api container requires that a Dandi Girder setup be available for some reason, so we have to spin up all containers.
=> Run "provision" container in the foreground

tools/migrate-dandisets.py
=> Add --only-metadata option to migrate-dandisets.py

dandi/models.py
SchemaKey provides type information for disambiguation of certain objects. This is being removed from the generated information. This PR removes the unset keyword which allows the const/Literal fields to be exported.
=> fix: remove unset fields to enable schemaKey

dandi/upload.py
This seems to be sufficient to avoid race condition between threads which
leads to uploaded_recs dict change, and python crashing while computing the sum
Closes #502
=> BF(workaround): get the list of entries with sizes before querying

dandi/metadata.py, dandi/tests/test_metadata.py
using `deepcopy(data)` in `migrate2newschema`, so it doesn't change the original data
closes #514
=> fix to migrate2newschema

dandi/cli/command.py
This PR modifies the way that logfile-only log messages are filtered out from the stderr logs to be more robust/standard/"the right way to do things" — specifically, by filtering on a custom extra log record attribute instead of the log message.
=> Better filtering of file-only log messages

dandi/cli/cmd_ls.py
=> Give `ls` a `--metadata` option

dandi/pynwb_utils.py, dandi/tests/test_utils.py, dandi/utils.py, setup.cfg
Ran into crash of dandi-cli tests on our docker `dandiarchive/nwb-healthstatus:pynwb-1.2.0` with some arbitrarily old hdmf before it got `__version__`.  I do not think we should puke like that so decided to resort to asking pkg_resources if no `__version__`
Learning typing while at it -- @jwodder, how to properly annotate for a Module?  please suggest a fix
=> Add and use get_module_version for cache tokens

dandi/metadata.py
assuming that `U` or `u`  value can be treated as `Unknown`
=> small fix of extract_sex

README.md
We need a release since I keep running into hdmf without `__version__`
=> DOC: minor tune up to README.md on installation instructions and WiP

dandi/cli/command.py, dandi/utils.py
This cuts off about a second and a half from the dandi command's load time.
=> Get hdmf, pynwb, h5py versions without importing

dandi/delete.py
=> Strip trailing slash from API URL used by delete()

dandi/download.py, dandi/tests/test_download.py
=> Fix & test for downloading by asset ID URL

dandi/utils.py
Closes #566
Result of  https://github.com/dandi/redirector/pull/40
=> BF: do not assume that service record of redirector is present/has url

dandi/dandiarchive.py, dandi/delete.py, dandi/tests/test_dandiarchive.py, dandi/tests/test_utils.py, dandi/utils.py
=> Switch default dandi instance to dandi-api based on redirector

dandi/dandiapi.py
Required by https://github.com/dandi/dandi-api/pull/236
As described in https://github.com/dandi/dandi-api/pull/236, the
original `.../versions/{version_id}/` has been updated to only return
the version metadata. Because clients are still relying on the Django
serialized information about the version, that data can now be found at
`.../versions/{version_id}/info/`.
=> Update for the version /info endpoint in dandi-api

dandi/tests/test_dandiarchive.py, dandi/tests/test_delete.py, dandi/utils.py
minimal patch to get `download` working after migration and girder being gone.
While at it, trying to fix up some tests as well which did not survive girder being gone
=> BF: "girder" record might be there but "url" might be None

dandi/cli/cmd_delete.py, dandi/delete.py, dandi/tests/test_delete.py
=> Give "delete" a --skip-missing option

tools/validate-api-against-girder.py
for total paranoia - reimplemented logic for recursion through girder folders.  So comparing that one also against the one we get from our existing helpers, and then against output from API.
it is still running, but TODOs
<details>
<summary>Full report</summary> 
```shell
$> python tools/validate-api-against-girder.py
DANDI:000003    101 assets the same
DANDI:000004    87 assets the same
DANDI:000005    148 assets the same
DANDI:000006    53 assets the same
DANDI:000007    54 assets the same
DANDI:000008    1328 assets the same
DANDI:000009    173 assets the same
DANDI:000010    158 assets the same
DANDI:000011    92 assets the same
DANDI:000012    297 assets the same
DANDI:000013    52 assets the same
DANDI:000015    210 assets the same
DANDI:000016    135 assets the same
DANDI:000017 …
```
=> a script to validate dandi-api collection listing against girder

.github/workflows/test.yml, tox.ini
This started out as a test to see what happened, but with the adjustment of pytest's warning settings, I've gotten the change to work.
=> Remove numpy pre-pinning in test.yml

dandi/consts.py, dandi/tests/fixtures.py, dandi/tests/test_dandiarchive.py, dandi/tests/test_utils.py, tox.ini
For https://github.com/dandi/redirector/issues/42.
=> Support specifying the dandi redirector via an env var

dandi/cli/cmd_download.py, dandi/cli/cmd_ls.py, dandi/cli/tests/test_ls.py, dandi/dandiarchive.py, dandi/delete.py, dandi/download.py, dandi/tests/test_dandiarchive.py, dandi/tests/test_delete.py
=> Restructure parse_dandi_url() return type

dandi/delete.py
=> Cut down on some code duplication in delete.py

dandi/cli/cmd_delete.py
=> DOC: Extend description for delete to point that it could be URL etc

dandi/tests/test_utils.py
This is needed for https://github.com/dandi/redirector/pull/47.
=> Make test_server_info use Docker fixture if DANDI_REDIRECTOR_BASE is set

dandi/cli/cmd_organize.py, dandi/tests/test_organize.py
We will just rely on users to populate it online without providing them
with any assistance locally since we do not upload dandiset.yaml
anyways.
Discussion/observation which triggered this change: https://github.com/dandi/dandi-cli/issues/614#issuecomment-832921269
=> RF: organize - should no longer alter dandiset.yaml

dandi/consts.py
There is now a staging API server set up at https://api-staging.dandiarchive.org, so it would be cool if dandi-cli could upload to it.
=> Add dandi-staging to known_instances

dandi/cli/cmd_download.py, dandi/cli/cmd_upload.py, dandi/cli/tests/test_download.py, dandi/download.py, dandi/tests/fixtures.py, dandi/tests/test_download.py, dandi/tests/test_upload.py, dandi/upload.py, dandi/utils.py, setup.cfg
Closes #365.
Does not include renaming.
=> Add "sync" option for upload & download

dandi/utils.py
=> Warn on ignored symlinks to directories

setup.cfg
since we are not at luxury to "redeploy" dandi-cli rapidly (installed by
users), I see no other way than this.
=> Pin dandischema to compatible 0.minor version

.github/workflows/test.yml
I think it is time to just switch to do testing on PR merges, and avoid testing on pushes to PR branches.
=> Run test workflow on pushes only on master

dandi/cli/cmd_ls.py, dandi/cli/tests/test_ls.py
=> ls --schema: Calculate digest for local assets

dandi/cli/tests/test_shell_completion.py
dandi's conda-forge build is failing on Windows in part because `SHELL` isn't set for some reason when passing the shell completion command to Bash.  This PR fixes that by always setting `SHELL` explicitly.
=> Fix a failing test on Windows on conda-forge

dandi/cli/cmd_shell_completion.py
dandi's conda-forge build is failing on Windows in part because the bash executable is named `bash.EXE`.  This PR fixes that by stripping off any ".exe" suffix (case insensitive) from the SHELL value before using it.
=> Fix a failing test on Windows on conda-forge (again)

dandi/metadata.py, dandi/upload.py
=> Add get_asset_metadata() function

dandi/cli/tests/test_shell_completion.py
It just doesn't work on conda-forge.
=> Skip shell completion test entirely on Windows

dandi/support/tests/test_iterators.py
with all the threading etc, I guess there is no way to guarantee it always
getting at least that single one before exception.  From one of the runs
in dandi-api:
https://github.com/dandi/dandi-cli/pull/706/checks?check_run_id=3030777195
_________________________ test_IteratorWithAggregation _________________________
dandi/support/tests/test_iterators.py:72: in test_IteratorWithAggregation
assert got == [0]
E   assert [] == [0]
E     Right contains one more item: 0
E     Full diff:
E     - [0]
E     ?  -
E     + []
=> BF(TST): Allow for IteratorWithAggregation to get nothing if reraise_immediately

.readthedocs.yaml
=> Add Readthedocs config

dandi/dandiapi.py, dandi/tests/test_dandiapi.py
I think the flaky tests we have been seeing are being caused by multiple
sequential celery tasks. Creating a new dandiset and uploading an asset
both trigger the validation task, but the first one is guaranteed to
fail. I think the test was noticing that first failure and quitting
immediately, instead of waiting the extra time required for the second
task to validate correctly.
Should fix dandi/dandi-api#393
=> Use timed wait in publish test

dandi/dandiapi.py
Closes #714.
Tenacity does not seem to support indefinite retrying for only one type of error.
=> Increase retries & wait times for API errors

.readthedocs.yaml, tox.ini
The docs try to document a couple test modules that import pytest, so that needs to be installed when building the docs.
Closes #717.
=> Install "test" extras when building docs

docs/source/conf.py
This field seems to be required by the EPUB builder, and the lack of it is causing the build on "latest" to fail.
Closes #717 (again).
=> Set "version" in docs/source/conf.py

docs/source/_static/custom.css, docs/source/conf.py
Default alabaster"s width is too narrow and causes too many word
and signature wraps.  I would leave it to the user to decide which
width they want.  someone with more CSS knowledge could make it a bit more dynamic
but default is really suboptimal IMHO
after preview is available, compare e.g. to https://dandi--718.org.readthedocs.build/en/718/modref/dandiarchive.html
=> Stretch the doc to the screen width

dandi/cli/command.py, setup.cfg
BadVersion was added in 0.2.2 thus boosting etelemetry version
=> ENH: exit with non-0 when "bad_version" of dandi-cli is used

dandi/dandiapi.py, dandi/exceptions.py, dandi/tests/test_dandiapi.py, dandi/upload.py
=> Make upload() fail if client & server schema versions are not in sync

dandi/cli/command.py, dandi/dandiapi.py, dandi/utils.py
=> Invoke etelemetry when constructing a DandiAPIClient; honor DANDI_NO_ET

dandi/metadata.py
I think time to assume that all NWB files would have .nwb extension I think.
This PR is maintaining prior behavior of re-raising the exception if allow_any_path is
False.  Otherwise -- and regardless if allow_any_path is True or not (thus
would not re-raise for non .nwb files even if not allow_any_path) - provide default
metadata record.
For upload it should be fine AFAIK even with the change  of behavior since we first
use allow_any_path to select .nwb files.
Closes #730
=> RF: attempt nwb metadata extraction only on .nwb, if fails -- warning

dandi/dandiarchive.py
=> Retry following redirects that return 404

dandi/upload.py
This was the only spot I could find where a status of "error" was not accompanied by a corresponding logging call.
Closes #735.
=> Log "error" statuses while uploading as ERROR log messages

dandi/dandiapi.py, dandi/tests/test_dandiapi.py
=> Test RemoteDandiset.refresh()

dandi/dandiapi.py
`requests.Session` objects start out with a `User-Agent` header already set, and so trying to set the header with `setdefault()` (which was chosen in order to not override a header set by the user on creating the Session object or set in `headers`) does nothing.
=> Correctly set User-Agent for client requests

dandi/tests/data/dandiarchive-docker/docker-compose.yml
RabbitMQ just released version 3.9.0, and it's not playing nice with
Celery. To get tests passing again, pin to version 3.8.
=> Pin rabbitmq version

dandi/tests/data/dandiarchive-docker/docker-compose.yml
The RabbitMQ docker image used in the test docker-compose configuration
had a bug, which necessitated pinning to an earlier version.
The bug has been fixed, so we can go back to using the official image.
=> Restore the rabbitmq version

dandi/dandiapi.py, dandi/dandiarchive.py, dandi/tests/test_dandiarchive.py, dandi/tests/test_download.py
Closes #723.
Note that the dandi-api Docker images are currently not building for some reason, and the latest image lacks support for the `/asset/<asset id>/` endpoint.  Hence, the tests will fail under the Docker build is fixed.
=> Support `/asset/<asset id>/download/` URLs

.github/workflows/test.yml
pynwb 2.0.0 was released on the 13th, and the rc/2.0.0 branch is no more.
=> Remove test against rc/2.0.0 branch of pynwb

dandi/dandiapi.py, dandi/tests/test_dandiapi.py
=> Give API resource classes `__str__` methods

dandi/pynwb_utils.py
So we do not use outdated results if dandischema was upgraded
without dandi-cli upgrade
=> Add dandischema into fscacher tokens for validate

dandi/tests/test_download.py
=> Use new published version of 000027 in tests

dandi/dandiarchive.py
=> Retry following redirects on 400 (not 404), 502, 503, & 504 up to 5 times

.github/workflows/test.yml, dandi/dandiapi.py, dandi/tests/fixtures.py, tox.ini
=> Add module docstring to dandiapi.py

dandi/tests/fixtures.py
See https://github.com/dandi/dandischema/issues/82 for more information.
Until the next rebuild of the dandi-api image on the Docker Hub, this PR will make dandi-cli's tests fail, so don't merge until then.  Once it's merged, the dandi-cli integration tests for dandischema (for the master version of dandi-cli, not the released version) will start passing again.
=> Update Docker Compose spin-up code for loss of --username option

dandi/dandiapi.py
Split off from https://github.com/dandi/dandi-cli/pull/775
=> Fix display of Dandiset validation errors

dandi/tests/data/dandiarchive-docker/docker-compose.yml, dandi/tests/fixtures.py
https://github.com/dandi/dandi-api/pull/538 is adding a scheduled job
which checks for Versions that need validation and validates them. The
default wait interval is 60 seconds, but it is configurable through an
environment variable, `DJANGO_DANDI_VALIDATION_JOB_INTERVAL`. Set this
environment variable to `5` so that the validation job runs every 5
seconds, which should be quick enough for `wait_until_valid`.
=> Specify DJANGO_DANDI_VALIDATION_JOB_INTERVAL

dandi/tests/data/dandiarchive-docker/docker-compose.yml, dandi/tests/fixtures.py
The Girder environment variables have been removed from dandi-api, so we no longer need to set them here.
=> Remove Girder envvars from Docker Compose setup

dandi/cli/cmd_validate.py, dandi/validate.py
=> Give `validate` command an `--allow-any-path` option

dandi/dandiapi.py, dandi/tests/test_dandiapi.py
Motivated by https://github.com/dandi/dandisets/issues/84.
=> Give `RemoteAsset` a `created` attribute

dandi/consts.py, docs/source/conf.py, docs/source/index.rst, docs/source/modref/consts.rst, docs/source/modref/dandiapi.rst, docs/source/modref/dandiarchive.rst, docs/source/modref/index.rst
This PR modifies the dandi Read the Docs docs to show the docstring for `dandi.dandiapi`; list the contents of `dandi.utils`, `dandi.support.digests`, and some of `dandi.consts`; change the titles for the module docs to names of the modules; adjust some prose; show "[source]" links next to Python objects; and a couple other things.
=> Show more documentation

dandi/cli/cmd_download.py, dandi/cli/cmd_ls.py, dandi/dandiarchive.py
=> Improve `dandi ls --help` and `dandi download --help` output

dandi/pynwb_utils.py, versioneer.py
Closes #522.
Note that I still don't know what the actual version format is for the version of the NWB standard used by a file.  As long as it's always something of the form `N(.N)*`, this will work, but if things like incrementing alphabetic suffixes are used, this will break.
=> Stop using distutils

README.md, setup.cfg
I also added a "Documentation" project URL link, which will show up on the left side of [the PyPI page](https://pypi.org/project/dandi/).
Closes #826.
=> Add Read the Docs badge to README

dandi/consts.py, dandi/dandiarchive.py, dandi/tests/test_dandiarchive.py
See https://github.com/dandi/helpdesk/issues/37#issuecomment-962037772
=> Convert DANDI: resource identifiers to lowercase when prepending "https://identifiers.org/" and tighten regex

dandi/dandiarchive.py
This PR:
* Eliminates retries on 400 responses (A 400 indicates that the client messed up, so it's highly unlikely that doing the same request again will go any better)
* Logs a WARNING message whenever an HTTP request made while resolving a resource identifier needs to be retried
* Lowers the number of retries for resolving resource identifiers from 5 to 4, thereby bringing the maximum time down from 18 and a half minutes to just under two minutes.
Closes #828.
=> Improve UX of failed redirects while resolving resource identifiers

.github/workflows/test.yml, setup.cfg, tox.ini
Python 3.10 was released on Monday, so we need to support it.
Note that the issue with installing h5py on 3.9 is gone, as pynwb and hdmf have relaxed their version requirements to work with the latest version of h5py, which provides wheels for 3.9.  However, at time of writing, the latest h5py does not provide wheels for 3.10, so I just changed the h5py handling from 3.9 to 3.10.
=> Test against Python 3.10

dandi/metadata.py, dandi/pynwb_utils.py, dandi/tests/test_pynwb_utils.py, tox.ini
=> Error on NWB files with external links

dandi/cli/cmd_organize.py, dandi/cli/cmd_upload.py, dandi/dandiarchive.py, docs/source/cmdline/dandi.rst, docs/source/cmdline/delete.rst, docs/source/cmdline/digest.rst, docs/source/cmdline/download.rst, docs/source/cmdline/index.rst, docs/source/cmdline/ls.rst, docs/source/cmdline/organize.rst, docs/source/cmdline/shell-completion.rst, docs/source/cmdline/upload.rst, docs/source/cmdline/validate.rst, docs/source/index.rst, docs/source/ref/index.rst, docs/source/ref/urls.rst
This PR expands the docs for the individual subcommands, adds a page documenting the root `dandi` command, and adds a single reference page listing the resource identifier patterns for other pages to link to.
=> Improve CLI documentation

dandi/tests/test_dandiapi.py, dandi/tests/test_delete.py, dandi/tests/test_download.py, dandi/tests/test_upload.py, dandi/utils.py
So that I don't have to keep writing `sorted(map(Path, find_files(r".*", [dirpath])))`
=> Add a wrapper function for the calls to `find_files()` in tests

dandi/keyring.py, dandi/tests/fixtures.py, dandi/tests/test_keyring.py, setup.cfg
This eliminates the dependency on the slow and occasionally-troublesome pyfakefs in favor of just monkeypatching `$HOME` to a temporary directory when testing out keyring support.
=> Replace the use of pyfakefs with a `tmp_home` fixture

dandi/__init__.py
This PR moves the "Basic logger configuration" comment in `dandi/__init__.py` to after the duecredit code, immediately before the actual logging code.  It serves as a minimal change in order to enable a release.
=> Move a comment

dandi/dandiapi.py
=> Include "dandiset" field in /uploads/initialize/ requests

setup.cfg
Want to see if we are all good with such an upgrade in the light of @dchiquito reporting error while downloading from the archive of 000027
<details>
<summary>detail from slack (not filed as an issue yet)</summary> 
```shell
Sadly I am having basic CLI problems. Running dandi download https://gui.dandiarchive.org/#/dandiset/000027 with dandi==0.34.0 is giving me this error:
Error: [{'type': 'array', 'items': [{'type': 'string'}, {'type': ['string', 'boolean']}], 'additionalItems': False}] is not of type 'object', 'boolean'
Failed validating 'type' in metaschema['properties']['definitions']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['properties']['additionalProperties']['$dynamicRef']['allOf'][1]['properties']['items']['$dynamicRef']['allOf'][0]:
{'$defs': …
```
=> upgrade dandischema requirement from 0.4.1 to 0.5.1 (~=)

dandi/dandiarchive.py
Closes #867.
Nonfunctional without https://github.com/dandi/dandi-archive/pull/831.
=> Make navigate() and navigate_url() auto-authenticate for embargoed Dandisets

dandi/metadata.py, dandi/utils.py
* `get_asset_metadata()` in `metadata.py` has been replaced by the `get_metadata()` methods of the `LocalAsset` class hierarchy in `files.py`
* `find_dandi_files()` in `util.py` has been replaced by `find_dandi_files()` in `files.py`
=> Delete functions (get_asset_metadata, find_dandi_files) obsoleted by PR #853

dandi/tests/fixtures.py, dandi/tests/test_dandiapi.py, dandi/tests/test_download.py, dandi/tests/test_files.py, dandi/tests/test_upload.py
This PR factors out the repeated code for creating a new test Dandiset and uploading files to it into a fixture.  It builds on top of/depends on #853 and thus has to be merged after it.
=> Add `new_dandiset` fixture

.github/workflows/typing.yml, dandi/cli/base.py, dandi/consts.py, dandi/dandiapi.py, dandi/dandiarchive.py, dandi/delete.py, dandi/download.py, dandi/files.py, dandi/metadata.py, dandi/misctypes.py, dandi/support/digests.py, dandi/tests/fixtures.py, dandi/tests/test_download.py, dandi/utils.py, setup.cfg, tox.ini
This PR adds a tox testenv and CI action for type-checking the code with mypy.  Note that much of the code base still does not have type annotations, which mypy is fine with; the plan is to annotate everything piecemeal so as not to end up with a massive PR that would likely create merge conflicts with everything else.
=> Enable type-checking

.github/workflows/test.yml, dandi/dandiapi.py, docs/source/examples/dandiapi-example.py, docs/source/modref/dandiapi.rst, tox.ini
This PR eliminates the use of `.. automodule:: dandi.dandiapi` to document `dandi/dandiapi.py` in favor of listing the classes explicitly with `autoclass::`.  This makes the following possible:
* Internal, implementation-defined classes (i.e., `APIBase` and `RemoteDandisetData`) can be excluded from the documentation
* The order in which the classes are listed can be controlled, and headers can be added to the listing
* Classes that are not meant for public construction can have their `__init__` signatures suppressed
The one downside (aside from now having to list classes manually) is that the `dandiapi.py` module docstring is now unused; this PR moves it to the reStructuredText document and stores the code example in an included external file so that the testing of the example via …
=> Organize & fine-tune dandi.dandiapi Sphinx docs

dandi/conftest.py, dandi/dandiarchive.py, dandi/dandiset.py, dandi/delete.py, dandi/download.py, dandi/exceptions.py, dandi/keyring.py, dandi/metadata.py, dandi/pynwb_utils.py, dandi/tests/fixtures.py, dandi/tests/test_dandiapi.py, dandi/tests/test_dandiarchive.py, dandi/tests/test_dandiset.py, dandi/tests/test_delete.py, dandi/tests/test_download.py, dandi/tests/test_fixtures.py, dandi/tests/test_keyring.py, dandi/tests/test_metadata.py, dandi/tests/test_organize.py, dandi/tests/test_pynwb_utils.py, dandi/tests/test_upload.py, dandi/tests/test_utils.py, dandi/upload.py, dandi/utils.py, dandi/validate.py
=> Add type-annotations to various files

dandi/dandiapi.py, dandi/download.py, dandi/tests/test_download.py, docs/source/modref/dandiapi.rst
This PR makes use of the `/assets/{asset_id}/info/` endpoint added by https://github.com/dandi/dandi-archive/pull/681 to construct `BaseRemoteAsset`s that have all of their "meta-metadata" from their Django serializations, thereby accomplishing the following:
* Add `created` and `modified` fields to `BaseRemoteAsset`
* Add `BaseRemoteBlobAsset` and `BaseRemoteZarrAsset` subclasses of `BaseRemoteAsset` with `blob` and `zarr` attributes, respectively
* These subclasses determine the return value of `asset_type` based on overloading rather than relying on `encodingFormat`
* `filetree` and `iterfiles()` have been moved from `RemoteZarrAsset` to `BaseRemoteZarrAsset`
* `BaseRemoteAsset.from_metadata()` has been replaced with `BaseRemoteAsset.from_base_data()`
* Support download of Zarrs …
=> Make use of `/assets/{asset_id}/info/` endpoint

dandi/tests/data/dandiarchive-docker/docker-compose.yml
Due to [this](https://github.com/minio/minio/issues/14235) bug in a recent minio release (filed by our very own @waxlamp), the cli integration tests in dandi-archive are failing, due to the containers not coming up correctly ([example](https://github.com/dandi/dandi-archive/runs/5057988507?check_suite_focus=true)). This change would pin the image version to the last known working version. This change can be reverted once the bug fix is released.
=> Pin minio image version

dandi/dandiapi.py, dandi/exceptions.py
This cuts down on a lot of simple repetition by adding a dedicated `HTTP404Error` exception class subclassing `requests.HTTPError` that is used specifically for 404 errors.
=> Add dedicated HTTP404Error exception class

setup.cfg
The only place tqdm is currently "used" is in a commented-out line in `dandi/organize.py`.
=> Remove unused tqdm dependency

dandi/files.py
For https://github.com/dandi/dandi-archive/pull/897
=> Specify Dandiset ID when creating a Zarr

dandi/files.py
See https://github.com/dandi/dandi-archive/pull/897#issuecomment-1041703701
=> Use full asset path as name of Zarr object

dandi/consts.py, dandi/dandiapi.py, dandi/files.py, dandi/tests/test_upload.py, tox.ini
=> Mint Zarr assets at start of upload and sync Zarr contents

dandi/cli/cmd_upload.py, dandi/tests/fixtures.py, dandi/upload.py, docs/source/cmdline/upload.rst
=> Make `dandi upload` look for dandiset.yaml in parents of common path

dandi/files.py
Before starting to upload a Zarr, the client compares the on-disk tree to the contents of the remote Zarr object being updated (if any).  Among other checks, if it finds a remote directory at the same path as a local file, it deletes the directory, which consists of deleting all of the files under it recursively.  Currently, the files are retrieved by making numerous queries to the API, but this PR changes the code to instead go through the already-fetched collection of remote files.
=> Don't repeat API requests when finding subdir files to delete before Zarr upload

dandi/organize.py, dandi/pynwb_utils.py, dandi/utils.py
if the external_files contain weblinks to media files, skip re-writing that attribute and do not do any copy/move operation.
=> skip handling URLs in external files references as we do for local paths

dandi/organize.py, dandi/tests/fixtures.py, dandi/tests/test_organize.py
If there happen to be multiple nwb files linked to one video file via the `ImageSeries.external_files`, the `move` option of `video_mode` will fail. This PR enforces the user to change the option to one of `copy/symlink/hardlink' instead by raising an Exception.
=> checking for duplicate video files in external_files

dandi/files.py, dandi/tests/test_files.py
=> Recognize video files as non-generic assets

dandi/cli/tests/test_digest.py, dandi/files.py, dandi/support/digests.py, dandi/support/tests/test_digests.py, setup.cfg
To accompany https://github.com/dandi/dandischema/pull/120
Cannot be tested until after dandischema 0.6.0 is released (and then further edits will be needed to update some test cases that hardcode checksums).
=> Update for change in Zarr checksum format

.pre-commit-config.yaml
Older black will hit an error if the system uses click 8.1.0 or newer.
See: https://github.com/psf/black/issues/2964#issuecomment-1080974737
@yarikoptic this is pertaining to the issue we discussed earlier this evening, and this commit solves it.
=> Black update

dandi/tests/fixtures.py
https://github.com/docker/compose/issues/9201 is the cause of https://github.com/dandi/dandi-archive/issues/1003, and this PR works around it.
=> Work around a bug in docker-compose

dandi/tests/data/dandiarchive-docker/docker-compose.yml
The celery worker in the docker-compose test configuration needs to
explicitly specify all queues that it monitors. Several queues have been
added recently so the worker definition needs to include those new
queues.
Fixes https://github.com/dandi/dandi-archive/issues/1011
=> Specify all queues in test celery worker

dandi/tests/fixtures.py
Reduced file size as per https://github.com/dandi/dandi-cli/issues/944#issuecomment-1088247834
They were already pretty small so this goes from 8KB to 6KB only.
Not entirely sure how 6KB are filled with 2 frames of 2x2 size, but I assume it's some encoding quirk.
`fps` changes seem to have no effect on size.
```python
chymera@decohost ~ $ cat lulu.py
def video_files(tmp_path):
video_paths = []
import cv2
import numpy as np
import os
video_path = f"{tmp_path}/video_files"
os.mkdir(video_path)
for no in range(2):
movie_file1 = f"{video_path}/test1_{no}.avi"
movie_file2 = f"{video_path}/test2_{no}.avi"
(nf, nx, ny) = (2, 2, 2)
writer1 = cv2.VideoWriter(
filename=str(movie_file1),
apiPreference=None,
fourcc=cv2.VideoWriter_fourcc(*"DIVX"),
fps=25,
frameSize=(ny, nx),
params=None,
)
writer2 = …
```
=> Smaller video files

dandi/tests/data/dandiarchive-docker/docker-compose.yml
These changes may possibly help resolve https://github.com/dandi/dandi-archive/issues/567.
* Limit celery concurrency to 1. Possibly having multiple workers running at the same time is causing a race condition.
* Upgrade the minio image version. The error might be happening when querying the minio container from the celery container, so possibly there is a minio bug that has been patched in the last 4 months.
=> Integration test config

dandi/tests/data/dandiarchive-docker/docker-compose.yml
Bug fix to #959
Apologies, I forgot to include the `DJANGO_` prefix to the env var.
=> Fix type in test docker-compose env var

dandi/bids_validator_xs.py, dandi/tests/test_bids_validator_xs.py
Miscellaneous but important improvements developed in parallel.
I will ping for review later, there are a few more.
=> Validator fixes: fallback to our version, skip dotdirs on windows, etc

dandi/utils.py
See https://github.com/dandi/dandi-archive/issues/1052
=> Strip trailing slash from URLs in `/server-info`

dandi/tests/test_utils.py
=> Mark `test_server_info` as xfailing

dandi/bids_validator_xs.py
New speedscope profile: https://ppb.chymera.eu/51d5f7.svg
=> performance: do not duplicate schema loading

dandi/bids_validator_xs.py, dandi/tests/test_bids_validator_xs.py
Very minor fix, prevents default logs from unceremoniously cluttering `/var/tmp/`.
=> keeping logs cleaner in dedicated directory

doc/design/python-api-1.md
prior discussion in https://github.com/dandi/dandi-cli/issues/249
=> Add new API design doc

dandi/consts.py
=> Increase Zarr depth limit to 7 directories

dandi/files.py
In order to cut down on (likely superfluous) API requests.
As discussed in Jitsi today.
=> Remove size comparison check when uploading Zarr entries

dandi/bids_validator_xs.py, dandi/cli/cmd_validate.py
trivial change, a couple of the return strings contained merged words like `aunique` due to string line breaking.
=> Whitespace for string returns

setup.py
Prepend the current directory to sys.path rather than appending it
in order to fix the build in PEP517 mode properly.  If the path
is appended and versioneer is installed on the system, the system
versioneer.py (i.e. the module used to install versioneer into projects)
is imported rather than the local file, and the build fails:
```pytb
Traceback (most recent call last):
File "/usr/lib/python-exec/python3.10/gpep517", line 4, in <module>
sys.exit(main())
File "/usr/lib/python3.10/site-packages/gpep517/__main__.py", line 136, in main
return func(args)
File "/usr/lib/python3.10/site-packages/gpep517/__main__.py", line 44, in build_wheel
wheel_name = backend.build_wheel(args.wheel_dir, args.config_json)
File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 244, in …
```
=> Prepend to sys.path to fix versioneer in PEP517 mode

dandi/cli/cmd_delete.py, docs/source/cmdline/delete.rst
internal implementation already had that option, so we just needed
to pass it through
Closes #993
=> ENH: delete - allow to specify --force in CLI

dandi/bids_validator_xs.py, dandi/cli/cmd_validate.py, dandi/cli/tests/test_cmd_validate.py, dandi/tests/test_bids_validator_xs.py
Addressing https://github.com/dandi/dandi-cli/issues/991
=> Logging validation warnings and errors

setup.cfg
There are several folders in `dandi/` that contain data files but no Python source code, and we want these to be included when dandi is installed.  Currently, these folders are automatically included by the combination of `graft dandi` in `MANIFEST.in` and `include_package_data = True` in `setup.cfg`, but because we set `packages` in `setup.cfg` to `find:` instead of `find_namespace:`, the folders themselves are not recognized by setuptools as packages.  [This combination of settings is deprecated](https://github.com/pypa/setuptools/issues/3340), and the setuptools developers recommend using `find_namespace:` instead of `find:` for such situations.
=> Properly include "data packages" in project

dandi/cli/tests/test_move.py
=> Make `test_move_command_too_few_paths` support `DANDI_DEVEL=1`

dandi/cli/cmd_service_scripts.py, dandi/cli/command.py, dandi/cli/tests/test_service_scripts.py, dandi/files.py, docs/source/cmdline/service-scripts.rst
=> Better cancellation of Zarr uploads

dandi/dandiapi.py, dandi/files.py
Closes #1033.
It turns out the idea I had to get the filesize ourselves and retry failures wouldn't work, as `requests` ignores user-supplied "Content-Length" headers.  Hence, we have to actually do the request and retry that.
An alternative approach would be to read the entire file into memory and PUT that, but I suspect the files get large enough that we want to avoid that.
=> Retry Zarr entry uploads that fail with "header ... implies functionality ... not implemented"

.github/workflows/lint.yml
=> Clone entire repo in "Lint" action

dandi/bids_utils.py, dandi/bids_validator_xs.py, dandi/cli/cmd_validate.py, dandi/tests/fixtures.py, dandi/tests/test_upload.py, dandi/upload.py, dandi/validate.py
@yarikoptic @satra still as draft, some things might still be weird, and need to come up with tests.
Eventually it will look like this (contains both normal and validation ignore usage), and if the number of invalid files is not 18k, the output also does not need to contain 18k lines :)
https://ppb.chymera.eu/1c32cb
=> Built-in BIDS support for `dandi upload`

dandi/cli/cmd_download.py
attn @waxlamp -- is it better?
=> DOC: describe the purpose for --instance in download

dandi/pynwb_utils.py
[`asscalar()`](https://numpy.org/doc/1.21/reference/generated/numpy.asscalar.html) has been deprecated since numpy 1.16, with `numpy.ndarray.item()` recommended instead.  Moreover, it was [completely removed in numpy 1.23](https://numpy.org/doc/stable/release/1.23.0-notes.html#expired-deprecations), released June 22.  Note that none of our tests seem to cover the case where an NWB has any probe_ids.
=> Replace numpy.asscalar() with numpy.ndarray.item()

dandi/move.py, dandi/tests/test_move.py
=> dandi move: Include all mismatches in error messages

dandi/move.py, dandi/tests/test_move.py
=> dandi move: Fix resolution of nonexistent dests when in a subdirectory

dandi/tests/data/dandiarchive-docker/docker-compose.yml, dandi/tests/fixtures.py
=> Remove redirector from Docker Compose setup

dandi/tests/fixtures.py, dandi/tests/test_upload.py, dandi/upload.py
Addressing: https://github.com/dandi/dandi-cli/issues/1055#issuecomment-1189149375
Example:
```console
chymera@decohost ~/src/bids-examples $ dandi upload -i dandi-staging eeg_cbm/
2022-07-19 14:17:00,460 [    INFO] Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-07-19 14:17:00,460 [    INFO] NumExpr defaulting to 8 threads.
2022-07-19 14:17:01,688 [ WARNING] BIDSVersion 1.0.2 is less than the minimal working 1.7.0+012+dandi001. Falling back to 1.7.0+012+dandi001. To force the usage of earlier versions specify them explicitly when calling the validator.
2022-07-19 14:17:02,435 [   ERROR] The `.*?/CHANGES$` regex pattern file required by BIDS was not found.
2022-07-19 14:17:02,435 [    INFO] Logs saved in …
```
=> User notification if datasets are invalid.

dandi/metadata.py, dandi/tests/test_metadata.py
=> Factor out common fields in nwb2asset() and get_default_metadata()

dandi/download.py, dandi/metadata.py, dandi/support/typing.py, dandi/tests/fixtures.py, dandi/tests/test_download.py, dandi/upload.py
This way instead of dumping all tracebacks at the end, some times for benign
FileExistsError -- they will be displayed neatly in pyout and also output
in detail in the log.
Closes https://github.com/dandi/dandi-cli/issues/1007
Closes #1030 (thanks @jwodder for pointing that out below)
- added explicit `on_error` option for `download_generator` so we could still regularly raise in `"-f debug"`
- includes commit to RF imports of type checks for older pythons so it is easier to find and later RF away for new minimal support versions of python.
=> BF: guard download_generator to not propagate errors

dandi/cli/tests/test_download.py, dandi/cli/tests/test_instances.py, dandi/consts.py, dandi/tests/test_dandiarchive.py, docs/source/cmdline/instances.rst
Troubleshooting dandi-archive locally and needed to download a new
dandiset from it. But it was not working because of
$> dandi -l DEBUG download -f debug http://localhost:8085/dandiset/000002
2022-05-05 16:46:10,698 [   DEBUG] Starting new HTTPS connection (1): rig.mit.edu:443
2022-05-05 16:46:10,961 [   DEBUG] https://rig.mit.edu:443 "GET /et/projects/dandi/dandi-cli HTTP/1.1" 200 579
2022-05-05 16:46:10,962 [   DEBUG] Running a newer version (0.39.5+4.gcca19df4.dirty) of dandi/dandi-cli than available (0.39.5)
2022-05-05 16:46:11,143 [   DEBUG] Creating converter from 7 to 5
2022-05-05 16:46:11,143 [   DEBUG] Creating converter from 5 to 7
2022-05-05 16:46:11,143 [   DEBUG] Creating converter from 7 to 5
2022-05-05 16:46:11,143 [   DEBUG] Creating converter from 5 to 7
2022-05-05 …
=> ENH: list localhost:8085 as the web UI for dandi-api-local-docker-tests 

dandi/metadata.py, dandi/tests/test_metadata.py
Adding range to the option for age. Using an ISO8601 extension for intervals, i.e:
`<ISOduration>/<ISOduration>` - both limits known
`/<ISOduration>` or `<ISOduration>/` - one limit is  unknown
`/` - both limits are unknown
Please check the tests for the new examples that will be covered, closes #1090 
I've realized that there is some redundant code for the iso formatting (some in utils.py), will try to clean it a bit later
=> Add support for age range 

.github/workflows/test.yml
[Ubuntu 18.04 is deprecated and will be removed from GitHub Actions by December 1.](https://github.com/actions/runner-images/issues/6002)
=> Update test.yml to use ubuntu-latest

dandi/dandiapi.py, dandi/tests/test_dandiapi.py
=> get_content_url(): If a HEAD fails, return the failing URL

setup.cfg
Closes #1111
Ref upstream: https://github.com/jaraco/keyring/issues/593
=> BF(workaround): blacklist 23.9.0 of keyring since introduced regression

.github/workflows/test.yml, dandi/files/bases.py, dandi/tests/fixtures.py, setup.cfg
Hey all, 
as a companion to the upcoming enforcement of more rigorous subject metadata requirements for DANDI upload (all taken care of by https://github.com/NeurodataWithoutBorders/nwbinspector/pull/247) it occurred to me that in order to both (i) prevent users from bypassing these requirements by downgrading their NWB Inspector version or (ii) prevent fewer future lower bound version bumps of the `nwbinspector` package on the DANDI requirements side; it would be best to simply check that the person is using the latest PyPI/conda-forge release of the package at time of validation.
I'm not really sure how to add a test for this though, let me know if you have ideas for that.
=> Check for usage of latest NWB Inspector release

dandi/organize.py, dandi/tests/test_organize.py
=> Detect link type for `organize` by linking from first src dir to dest dir

dandi/tests/fixtures.py
increasing number of trials to connect to dandisets in `docker_compose_setup`
@jwodder @yarikoptic - closing my tabs, restarting laptop, updating docker didn't help, still was timing out...
=> increase number of trials in docker_compose_setup to 25

dandi/dandiapi.py, dandi/tests/test_dandiapi.py
=> Update client-side publication workflow

dandi/dandiapi.py
to possibly avoid confusions like
https://github.com/dandi/dandi-cli/issues/1130
or should we go for `.info`?
=> ENH: lgr.debug that we are using DANDI_API_KEY provided key

.github/dependabot.yml, .github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/typing.yml
We are currently using older versions of the updated GitHub Actions actions, and these older versions still use Node 12, [which is deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
This PR also configures Dependabot to create PRs updating workflows whenever a new version of a used action is released, as discussed in https://github.com/datalad/datalad-extensions/pull/105.
=> Update GitHub Actions action versions

dandi/dandiapi.py
I don't know when the `/dandisets/:id/versions/:id/assets/:id/info/` endpoint was added, or when `/assets/:id/info/` started returning metadata, but I'm glad nonetheless.
=> Simplify implementations of `get_asset()` methods

dandi/cli/tests/test_digest.py, dandi/support/digests.py, dandi/support/tests/test_digests.py
@yarikoptic Please release this so I can use it in backups2datalad.
=> Make internal Zarr-checksumming tree types support empty Zarrs

dandi/files/zarr.py
Fixed a bug seen in https://github.com/dandi/dandi-cli/issues/1028#issuecomment-1282761146.
=> Don't try to cancel failed Zarr uploads twice

DEVELOPMENT.md, dandi/tests/fixtures.py
=> Add `DANDI_TESTS_PULL_DOCKER_COMPOSE` envvar

dandi/utils.py
I realized while investigating https://github.com/dandi/dandi-archive/issues/1336 that `list_paths()` is ignoring dotfiles & dotdirs, which could theoretically lead to a test not behaving properly when such files are present in a Dandiset or Zarr.
=> Make `list_paths()` include dotfiles

dandi/cli/cmd_validate.py, dandi/cli/tests/test_cmd_validate.py, dandi/files/bases.py, dandi/files/bids.py, dandi/files/zarr.py, dandi/pynwb_utils.py, dandi/tests/fixtures.py, dandi/tests/test_files.py, dandi/validate.py, dandi/validate_types.py, setup.cfg
=> Structured validation results

dandi/cli/tests/test_digest.py, dandi/download.py, dandi/files/_private.py, dandi/files/zarr.py, dandi/support/digests.py, dandi/support/threaded_walk.py, dandi/tests/test_download.py, dandi/tests/test_files.py, dandi/utils.py
=> Exclude special dotfiles from Zarrs

dandi/tests/fixtures.py, dandi/tests/test_validate.py
Error [fixed upstream](https://github.com/bids-standard/bids-specification/pull/1346#event-7696972438) but it was the specification schema rather than the example data which was broken, so we won't have access to it until the new release; removing test dataset from whitelist until then.
=> Fixed logic and commented a temporarily broken BIDS (lacking README) dataset

dandi/cli/cmd_validate.py
With that numpy style Parameters --help looks ugly and duplicates click produced help.
❯ dandi validate --help ecephys_tutorial.nwb
Usage: dandi validate [OPTIONS] [PATHS]...
Validate files for NWB and DANDI compliance.
Exits with non-0 exit code if any file is not compliant.
Parameters ----------
grouping : str, optional     A string which is either "", "error", or "path"
— "error" not yet implemented.
Options:
-g, --grouping [none|path]  How to group error/warning reporting.
--help                      Show this message and exit.
I remember asking for this change but it was missed.
=> Remove Parameters description from docstring used by click

dandi/pynwb_utils.py
Fixes https://github.com/dandi/dandi-cli/issues/917
Which came from https://github.com/dandi/helpdesk/discussions/43
Replaces https://github.com/dandi/dandi-cli/pull/1036
Newest version of PyNWB supports validation against cached namespaces (and indeed this is now the default).
I've updated the usage here in a minimal way to both support older PyNWB versions (my other thought was to bump the version in the `setup.cfg`, but IDK what your policy or view is on that) that do not offer this feature as well as the newest version that supports it as a simple adjustment to the way the `pynwb.validate` function is called.
=> Use cached namespace validation

dandi/cli/tests/test_cmd_validate.py
The test in question was failing because the `validate` command was exiting nonzero.
@TheChymera Seeing as the sample file was expected to fail validation, exactly why was the command expected to exit successfully, and what changed?
=> Update `test_validate_nwb_path_grouping` test

dandi/files/_private.py
The latest release of mypy now detects an error in our type annotations, which this PR fixes.
=> Fix typing error under mypy 0.990

dandi/tests/test_dandiapi.py
The blocking issue, https://github.com/dandi/dandi-archive/issues/1109, was resolved.
=> No longer mark `test_rename_type_mismatch` as xfailing

dandi/cli/tests/test_cmd_validate.py, dandi/files/bases.py, dandi/tests/fixtures.py
Addressing https://github.com/dandi/dandi-cli/issues/1158
The issue with the latter is that for validation via DANDI there is only one none-critical type of error, namely [`check_data_orientation`](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/54ac2bc7cdcb92802b9251e29f249f155fb1ff52/src/nwbinspector/internal_configs/dandi.inspector_config.yaml#L10). Though going by the comment that too appears to be temporary.
@CodyCBakerPhD (1) do you know how I could create a test case for this if this will likely be long-term-stable behaviour or (2) is there anything else we could add as `BEST_PRACTICE_VIOLATION` (apparently the second-highest criterion for NWBI errors) so that we can check warning reporting functionality?
=> Renamed failing test, added prospective use case for NWBI warning.

dandi/cli/cmd_validate.py
Addressing issue raised here: https://github.com/dandi/dandi-cli/pull/1165#issuecomment-1329566207
=> Corrected reporting function logic to complete group message variable

README.md
Edit readme for stylesheet compliance/grammar/clarity/consistency.
=> dandi-cli readme edit

dandi/cli/tests/test_cmd_validate.py, dandi/cli/tests/test_command.py, dandi/files/__init__.py, dandi/files/_private.py, dandi/files/bases.py, dandi/organize.py, dandi/tests/fixtures.py, dandi/tests/test_files.py, dandi/tests/test_organize.py, dandi/validate.py, dandi/validate_types.py
=> Add validation of filepaths for non-BIDS NWB assets

dandi/pynwb_utils.py
It also caused another kaboom within hdmf bubbling up through nwbinspector, filed https://github.com/NeurodataWithoutBorders/nwbinspector/issues/329
=> BF: convert str errors from checking nwb version into proper ValidationResult

dandi/cli/cmd_organize.py, dandi/consts.py, dandi/organize.py, dandi/tests/test_organize.py, docs/source/cmdline/organize.rst
=> Allow user to specify mandatory (if not empty) fields in organize

dandi/dandiapi.py, dandi/download.py, dandi/files/zarr.py, dandi/tests/test_dandiapi.py, dandi/tests/test_files.py, dandi/tests/test_upload.py, docs/source/modref/dandiapi.rst
Blocked by https://github.com/dandi/dandi-archive/pull/1394.
=> Update client for change in Zarr entries API

dandi/tests/test_upload.py
Closes: https://github.com/dandi/dandisets/issues/220
The idea is to add a test which ensures that the upload code produces BIDS assets for which the correct data can always be retrieved. Currently we just check a few of the files being uploaded. I think it already works in any case, but would be a good add-on test.
@yarikoptic @jwodder any ideas how I can access the metadata of the remote asset? I tried to look at other tests which check metadata, but thus far I haven't found anything that does that.
=> Upload test to check for metadata

dandi/dandiapi.py
The new Zarr entry pagination endpoint uses "next" URLs with a format that is not amenable to parallelization, which means that currently a warning is emitted whenever a Zarr's entries are paginated through.  This PR removes the warning.
=> Don't warn on unexpected formats for "next" page URLs

dandi/upload.py
Reported by a user in slack to be unable to upload a file, although validation did not report any errors.  Apparently we did not log errors and it was impossible to figure out what is going on.  So I have also added logging of those validation errors, without any custom serialization into a string so we log the most complete (and possibly the most useful since provides information on paths within file etc) representation.
Closes #1185
=> Fail upload only for validation ERRORs and not necessarily WARNINGs or HINTs + log all errors

dandi/utils.py
The problem was that it would not work whenever path is relative path -- it would simply not go up the hierarchy since parents would not include parent directory above current directory so we would not be able to determine the parent above CWD given relative path from CWD.
As a side effect we change return value of find_parent_directory_containing to always be absolute path
Closes #1187 
TODOs
=> RF/BF: make find_parent_directory_containing operate on absolute path

README.md
address 3 items outstanding from review in PR #1170
=> Further improve README.md: point to specific sections of handbook, remove lengthy `dandi ls --help` example

dandi/cli/tests/test_cmd_ls.py, dandi/files/bids.py, dandi/metadata.py, dandi/tests/fixtures.py, dandi/tests/test_metadata.py
Closes: https://github.com/dandi/dandi-cli/issues/1172
=> Joint BIDS-NWB metadata extraction.

tox.ini
Recent versions of Docker and/or Docker Compose require the `$USER` envvar to be set, yet tox unsets this envvar by default.  This PR fixes that.
=> Pass $USER to tox envs

dandi/metadata.py, tox.ini
This silences some typing errors related in some inscrutable way to the latest version of `retrying`.  It also unrestricts the maximum mypy version so that we can use the newly-released v1.0.
=> Fix type errors; unbound mypy

dandi/dandiapi.py, docs/source/modref/dandiapi.rst
=> Make `RemoteDandiset.get_version()` return a `VersionInfo` instance with validation error fields

dandi/files/bases.py, dandi/files/zarr.py, dandi/misctypes.py, dandi/pynwb_utils.py
Might still be incomplete since I left  in place the odd dichotomy of results in validation depending on either schema_version is provided or not, as emphasized in the tests at https://github.com/dandi/dandi-cli/blob/HEAD/dandi/tests/test_files.py#L313 . @jwodder @TheChymera do you remember a reason why we did it this way?
meanwhile I made `LocalAsset` to always validate against schema even if a `schema_version` is not provided and that might be going against some logic which is pointed to above.  But I think we should simplify/harmonize it here one way or another: we might want to always validate against everything possible and then results just filtered, or would need to pass some *filtering* option (e.g. listing validation `id` prefixes thus to enable only some) to select which …
=> BF+RF validation

.github/workflows/test.yml, setup.cfg, tox.ini
Python 3.11 was released on October 24, so it's time to start testing against it.
Note: I expect this PR to fail for the next few weeks until numpy makes a 3.11-compatible release.
=> Test against Python 3.11

dandi/delete.py, dandi/validate.py, docs/source/cmdline/index.rst, docs/source/modref/index.rst
as consequence, lower the other two levels to Mid/Low levels (unless there is objection)
but how to point to the specific functions (e.g. `download.download`) instead of full modref -- @jwodder could you make it happen since I have tried some ways and keep making sphinx unhappy
=> List in documentation the "high level" interfaces corresponding to CLI

.github/workflows/test.yml
We scared it well enough that it returned immediately after ;)
This reverts commit 446cf7b8736939cbfe642eb8326d90c77cd10e60.
=> Revert "Temporarily disable all tests which talk to obolibrary" - ontobee said to be back

dandi/tests/test_metadata.py
`test_metadata.py::test_parseobourl[http://purl.obolibrary.org/obo/NCBITaxon_10116-value1]` is currently failing because the obolibrary resource now lists "rat" rather than "Norway rat" as the first `oboInOwl:hasExactSynonym` entry.
=> Update `parse_purlobourl()` test for change to rat metadata

dandi/files/__init__.py
Ref: https://github.com/dandi/dandi-cli/issues/1212
=> BF: add missing f- for a string

dandi/cli/cmd_download.py, dandi/download.py, dandi/support/iterators.py, dandi/tests/test_download.py, docs/source/cmdline/download.rst
Closes #1217.
Note that I'm not sure about whether the aggregating iterator works correctly, as when I tried downloading multiple URLs at once, the aggregate stats were only shown once the program finished.  At least one problem is that `it.finished` will be briefly true between URLs.
=> download: support for downloading multiple URLs at once; dandiset path is now included in the report

dandi/tests/test_metadata.py
fsspec installed only in "[extras]" extra_requires, so not by default. I tested that it is enough of "pip install fsspec" without "[http]" extras and test passes then.
Discovered needed while downstream testing  https://github.com/dandi/dandi-schema/pull/100 . Since we are installing `dandi` as released IIRC also for downstream in dandi-archive, I am marking this one for release so we get green again.
=> skip test_nwb2asset_remote_asset if no fsspec installed

dandi/cli/cmd_validate.py
Really minor fix I noticed while working on something else, hence the unfitting branch name.
=> Corrected docstring

tox.ini
Type-checking of pydantic types is broken in many respects under mypy 1.1.1 (See https://github.com/pydantic/pydantic/issues/5148), so until pydantic publishes a new release with a fix, we need to use an older mypy in order to get type-checking to pass.
=> Restrict mypy to pre-v1.1.1

tox.ini
This reverts commit 042eff5e7feb555caf19ec4786001445c98193b5 / #1246.
Pydantic 1.10.6, released yesterday, fixes the mypy integration.
=> Revert "Restrict mypy to pre-v1.1.1"

dandi/download.py, dandi/files/bids.py, dandi/metadata.py, dandi/support/typing.py, dandi/tests/test_upload.py, setup.cfg
Blocked by https://github.com/dandi/dandi-archive/issues/1520.
There are still some typing errors that will be resolved once https://github.com/dandi/dandi-schema/pull/163 is merged & released.
Closes #1249
=> Update for dandischema 0.8.0

.github/workflows/test.yml, DEVELOPMENT.md, dandi/files/zarr.py, dandi/upload.py
=> Log results of `requests.utils.super_len()` when `DANDI_DEVEL_INSTRUMENT_REQUESTS_SUPERLEN` is set

dandi/tests/test_validate.py, dandi/validate.py
This is what could happen before this:
```
(dev) [deco]~/src/bids-examples/asl003 ❱ dandi validate .
2023-04-03 12:43:56,852 [    INFO] Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-04-03 12:43:56,852 [    INFO] NumExpr defaulting to 8 threads.
2023-04-03 12:43:58,230 [    INFO] Logs saved in /home/chymera/.cache/dandi-cli/log/20230403164355Z-7402.log
Error: Path '.' is not inside Dandiset path '/home/chymera/src/bids-examples/asl003'
```
=> validate: resolved issues with relative path input

dandi/tests/test_validate.py
`validate()` is a generator function, and so calling it does not run any code unless the returned value is iterated over.
=> Fix `test_validate_relative_path`

dandi/tests/test_files.py
=> Make test NFS-safe

dandi/pynwb_utils.py
ref: https://github.com/dandi/helpdesk/discussions/95#discussioncomment-5687405
apparently we started to fail to extract metadata due to some warning being spitted out that file is not open for writing whenever we do not even expect it to open for writing.  Not yet entirely sure what was happening there since user reported that the issue was resolved by upgrade of h5py. But here it is worth addressing the warning anyways:
H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
@jwodder  - can you …
=> Explicitly open h5py.File as read-only where we read it

dandi/files/bases.py, dandi/metadata.py, dandi/organize.py, setup.cfg
The test suite has been failing for the past few days with the following causes:
- Calls to `nwbinspector.inspect_nwb()` (used to validate NWB files) were returning an error message reading:
> The API function 'inspect_nwb' has been deprecated and will be removed in a future release! To remove ambiguity, please call either 'inspect_nwbfile' giving a path to the unopened file on a system, or 'inspect_nwbfile_object' passing an already open pynwb.NWBFile object.
and this ended up in the set of validation errors.  I have replaced `inspect_nwb()` with `inspect_nwbfile()`.
- [A bug in recent versions of `ruamel.yaml`](https://sourceforge.net/p/ruamel-yaml/tickets/461/) was causing a certain spot in `organize.py` to fail.  I addressed this by removing the `age.pop("units", None)` line, which …
=> Use `inspect_nwbfile()` instead of `inspect_nwb()`; address bug in recent `ruamel.yaml` versions

.github/workflows/test.yml
If a commit is pushed while tests are still running on that branch, the older tests will currently continue to run to completion, likely delaying the start of the tests for the newer commit.  This PR causes any still-running tests to be automatically cancelled when new tests start on the same branch.
=> Cancel any still-running tests when pushing to a branch or PR

dandi/tests/test_files.py, setup.cfg
`test_files.py::test_dandi_file_zarr_with_excluded_dotfiles` keeps intermittently failing on NFS, so this PR uses pytest-rerunfailures to rerun it up to ten times until it succeeds.
=> Retry test that intermittently fails on NFS

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/typing.yml, .readthedocs.yaml, dandi/validate.py, setup.cfg
To be merged after the prospective `0.7.0` release of BST.
=> Bidsschematools 0.7.0 API usage update

dandi/dandiset.py, dandi/files/__init__.py, dandi/files/bids.py, dandi/files/zarr.py, dandi/move.py, dandi/organize.py, dandi/upload.py, dandi/utils.py
Closes #1289.
@yarikoptic I can't tell which uses of `exists()` in `dandi/organize.py` should be replaced with `lexists()` and which rely on the file actually being present/openable.  Could you go through the file and check the uses of `exists()` there?
=> Don't treat certain broken symlinks as absent files

setup.cfg
Since we no longer support Python 3.7.
=> Drop dependency on importlib-metadata backport for Python 3.7

dandi/dandiapi.py
Blocked by https://github.com/dandi/dandi-archive/pull/1579.
Replaces #1288.
=> Update `asset_validation_errors` structure

dandi/dandiapi.py
This brings the CLI up to parity with https://github.com/dandi/dandi-archive/pull/1548. The tldr is that it's not enough to check the version status to know if a version is publishable since the assets must also be valid.
cc @AlmightyYakob @jwodder
=> Fix wait_until_valid to properly wait for a publishable version

dandi/consts.py, dandi/organize.py, dandi/tests/test_organize.py
ref: #1314 
TODO outside of this PR:  check/decide on possibility of `organize` to actually automagically assign such `desc`... unlikely since the space is huge...
=> ENH: Add support for _desc- entity to label different processings of a file

dandi/dandiapi.py, dandi/files/bids.py, dandi/tests/fixtures.py, dandi/tests/test_upload.py
could not run tests locally unfortunately . See first commit for more details
Closes #1307
TODOs:
=> Fix uploading Zarr within a BIDS dataset; typing-check guided fix for handling requests exception

tox.ini
locally (vcr 5.1.0) it causes tests to fail, possibly masking another issue ref: https://github.com/dandi/dandi-cli/issues/1332 which I otherwise fail to reproduce locally
=> Ignore unclosed connection resource warning from VCR

dandi/dandiarchive.py, dandi/tests/test_dandiarchive.py, docs/source/ref/urls.rst
Per @AlmightyYakob observation in
https://github.com/dandi/dandi-archive/issues/1546#issuecomment-1478119271
If you don't see a problem with such an approach, please finish it up (leaner code if any , tests) @jwodder so we could declare that issue in the archive addressed.
Closes #1256
=> `?location` parameter in URLs can only point to a folder

dandi/download.py, dandi/tests/test_download.py
Fix https://github.com/dandi/dandi-cli/issues/1339
Add in missing -dt term so ETA counts down correctly :)
to quote @NickleDave : "I have changed but one line, yet achieved enlightenment in the path I took to change it" 
https://neuromatch.social/@nicholdav/111297136870307787
(davey nickles i hereby see your one line PR and raise you one line PR with 40 line test)
=> Add missing term in ETA calculation

dandi/cli/tests/data/update_dandiset_from_doi/biorxiv.vcr.yaml, dandi/cli/tests/data/update_dandiset_from_doi/elife.vcr.yaml, dandi/cli/tests/data/update_dandiset_from_doi/jneurosci.vcr.yaml, dandi/cli/tests/data/update_dandiset_from_doi/nature.vcr.yaml, dandi/cli/tests/data/update_dandiset_from_doi/neuron.vcr.yaml, dandi/cli/tests/test_service_scripts.py
I believe that somehow some upgrade among
```
❯ wdiff -3 /tmp/f1 /tmp/f2
====================================================================== [-06/github/cron/20231006T060312/0c1d4a0/Tests/5197/test-]{+07/github/cron/20231007T060245/0c1d4a0/Tests/5198/test+} ======================================================================
[-dependencies.txt:2023-10-06T06:05:18.6948668Z-] {+dependencies.txt:2023-10-07T06:04:51.1091526Z+}
======================================================================
[-boto3-1.28.61 botocore-1.31.61-] {+boto3-1.28.62 botocore-1.31.62+}
======================================================================
[-entrypoints-0.4-]
======================================================================
[-numcodecs-0.11.0-] {+numcodecs-0.12.0+} …
```
=> Re-record VCR tapes using newer versions of libraries

dandi/cli/cmd_organize.py, dandi/organize.py, dandi/tests/test_organize.py
Recent usage of the DANDI API in the NWB GUIDE revealed a sporadic `joblib` issue that results in segmentation faults - no clue what actually causes it for some users, but the best solution we have for now is to just expose job usage directly
Where should tests for this go?
=> Expose number of jobs to organize

setup.cfg
The tests have been failing for the past four days due to [an issue with the latest version of `responses`](https://github.com/getsentry/responses/issues/689).  This PR excludes the version in question from use.
=> Don't use buggy version of `responses`

.codespellignore, setup.cfg
Having that `.codespellignore` file there bothered me.
=> Move words ignored by codespell from `.codespellignore` to `setup.cfg`

dandi/cli/command.py, setup.cfg, tox.ini
[`appdirs` is deprecated](https://github.com/ActiveState/appdirs#readme), and [`platformdirs`](https://github.com/platformdirs/platformdirs) is its replacement.
=> Replace appdirs with platformdirs

dandi/organize.py, dandi/tests/test_organize.py
black for some reason introduced some changes, I didn't fight.
=> Sanitize spaces and ,s in organized filenames

dandi/cli/cmd_ls.py, dandi/cli/command.py, dandi/cli/formatter.py, dandi/dandiapi.py, dandi/download.py, dandi/due.py, dandi/organize.py, dandi/pynwb_utils.py, dandi/support/pyout.py, dandi/tests/fixtures.py, dandi/tests/skip.py, dandi/tests/test_keyring.py, dandi/tests/test_upload.py, dandi/utils.py
Plus some manual corrections of the results.
=> Run `pyupgrade --py38-plus` on source

dandi/validate_types.py
That attribute only has a purpose when supporting both Python 2 and Python 3, which we are not doing.  CC @TheChymera.
=> Remove `_order_` attribute from `Severity` enum

dandi/consts.py, dandi/dandiarchive.py
The classes weren't using Pydantic's validation features, so this will be slightly faster.
=> Convert dandiarchive URL classes from pydantic models to dataclasses

dandi/cli/cmd_move.py
I suspect the error in question only started being emitted when mypy 1.7.0 was released on the 10th.
=> Fix typing error

dandi/metadata.py
This PR merges duplicate a duplicate entry in the current `species_map` variable in `dandi/metadata.py`. We are using this variable in the NWB GUIDE to [populate an autosuggestion dropdown](https://github.com/NeurodataWithoutBorders/nwb-guide/pull/513) for Subject.species values.
=> Merge duplicate entries in species_map

.github/workflows/test.yml
Inspired by https://github.com/dandi/dandi-cli/pull/1312 and ongoing work for Zarr based backend for NWB.
=> Install also hdmf from git in the dev-deps CI run

dandi/files/zarr.py, dandi/support/digests.py, setup.cfg
- We can't update to `zarr_checksum` 0.3.0 yet, as that requires Pydantic v2.
- As `zarr_checksum` gained type annotations in dandi/zarr_checksum#21, we can remove its override from the mypy config.
- Since dandi/zarr_checksum#17 was merged, it's now safe to import `zarr_checksum` at the top level of a module.
- Fixed a typing error caused by importing `ZarrChecksumTree` from the top level of `zarr_checksum` despite it not being listed in `zarr_checksum.__all__`, which triggered a typing failure due to our mypy configuration containing `implicit_reexport = False`.  (This error could only be detected after `zarr_checksum` started shipping a `py.typed` file.)
=> Update for `zarr_checksum` 0.2.12

dandi/consts.py, dandi/dandiapi.py, dandi/download.py
=> Set 30-second connect & read timeout when downloading files

dandi/upload.py
=> Repeatedly double-check return values of zero when spying on `super_len()`

dandi/misctypes.py, dandi/tests/test_dandiapi.py
@yarikoptic I am marking this for release as it is a blocker for https://github.com/dandi/dandi-infrastructure/issues/163.
=> Properly open filehandles for `RemoteReadableAsset`s

.gitignore, README.md, dandi/cli/cmd_validate.py, docs/source/cmdline/validate.rst
- Add a note that `dandi validate` works to ensure BIDS compliance.
=> Minor docs update for `dandi validate`

dandi/files/bases.py, dandi/files/zarr.py, dandi/tests/test_utils.py, dandi/utils.py
=> Double-check file sizes before & after uploading

README.md, dandi/cli/cmd_organize.py
- Updated the summary line in the docstring to specify that `dandi organize` works for NWB files (and not BIDS datasets).
=> Minor update to `organize` docstring

dandi/download.py, dandi/tests/test_download.py
Closes #1383.
Note that this feature only applies to `dandi://` URLs, as GUI and API URLs cannot refer to a specific asset by path in the first place.
Note that this re-interpretation of `dandi://` URLs only happens when downloading and not when a `dandi://…/dandiset.yaml` URL is supplied to a `move`, `delete`, `ls`, or `reextract-metadata` command (I think those are all the places that `dandi://` URLs are accepted), as it wouldn't make sense for most of those.
=> `dandi download dandi://…/dandiset.yaml` now downloads `dandiset.yaml`

dandi/cli/tests/test_service_scripts.py
The `update-dandiset-from-doi` tests are currently failing because they test against the Dandisets' final `citation` fields (among others), which the Archive automatically populates based on the year the Dandisets were created (among other things), and so our expected output is no longer accurate as of the new year.
=> Fix service script tests for change in autogenerated date

dandi/files/zarr.py, dandi/support/digests.py, dandi/support/tests/test_digests.py
And rewrite it in terms of `zarr_checksum`
Part of dandi/dandi-schema#209
=> Adopt `dandischema.digests.zarr.get_checksum()` to dandi-cli: use zarr_checksum library constructs instead of copies in dandischema

tox.ini
=> Ignore irrelevant deprecation warning from pandas

setup.cfg
Now that https://github.com/dandi/zarr_checksum/pull/53 has been merged & released, we should be able to use the latest version of `zarr_checksum` without having to update Pydantic first (#1381).
=> Update zarr_checksum dependency to `~= 0.3.2`

dandi/dandiapi.py
=> Add notes to docs about `get_metadata()` vs. `get_raw_metadata()`

dandi/files/bases.py
Currently DANDI will fail to work due to this import specifically if etelemetry is not present.
All other code points where etelemetry is needed are either caught exceptions or controlled by `NO_ET`.
Let me know if I should do this differently.
=> Failsafe etelemetry import

dandi/dandiapi.py, dandi/tests/fixtures.py, dandi/tests/test_dandiapi.py
=> Add arguments for API query parameters when fetching all Dandisets; support creating embargoed Dandisets

dandi/metadata/util.py
yarl doesn't really seem like it would help with this bit, but I came up with a different way to make the code arguably cleaner.
=> Clean up URL parsing in `extract_species()`

dandi/dandiapi.py, dandi/delete.py, dandi/tests/test_delete.py, dandi/utils.py, setup.cfg
=> Use `yarl` to clean up some code

setup.cfg
testing started to fail
With current release of dandi-schema our testing starts to fail, but dandi-archive seems needing CI fixing first to also 
make upgrade possible. So as a quick resolution to avoid ill effects on users etc, I think we should restrict version
refs:
- https://github.com/dandi/dandi-archive/pull/1893
- (blocker) https://github.com/dandi/dandi-archive/issues/1894
=> Do not allow dandischema 0.10.1 - new schema not yet supported by dandi-archive

setup.cfg
This reverts commit ca4c1702e46dae5ca4db2886e2700fe1f408bb31.
dandi-archive supports new schema now, we should be fine to proceed.
=> Revert "Do not allow dandischema 0.10.1 - new schema not yet supporteed by dandi-archive"

dandi/tests/fixtures.py
dandi-archive requires this command to be run as part of system initialization in order to initialize the database to serve as a Django cache backend. It must be run in order for any endpoint with caching enabled to work properly. See the set up instructions for docker-compose: https://github.com/dandi/dandi-archive/blob/master/DEVELOPMENT.md#initial-setup
Up until this point, the only endpoint with caching enabled was `/api/stats/`, and presumably the CLI has no need to hit that in testing so this went unnoticed. However, the rate limiting introduced in https://github.com/dandi/dandi-archive/pull/1899 also makes use of the database cache backend, and thus the CLI tests are failing on that PR.
=> Add missing command to `dandi-archive` docker compose fixture

.github/workflows/test.yml, dandi/conftest.py, dandi/tests/test_metadata.py
=> Xfail flaky ontobee tests, unless running daily tests

dandi/cli/cmd_download.py, dandi/cli/cmd_ls.py, dandi/dandiarchive.py
I pulled the "primer" from https://dandi.readthedocs.io/en/latest/ref/urls.html#resource-ids
Do you think that helps enough?
(I also added to dandi_ls since it reused the same resource id doc)
`$ dandi download --help`
```
Usage: dandi download [OPTIONS] [URL]...
Download files or entire folders from DANDI.
dandi commands and accept URLs and URL-like identifiers called
<resource ids> in the following formats for identifying Dandisets, assets, and asset
collections.
Text in [brackets] is optional.  A server field is a base API or GUI URL for
a DANDI Archive instance.  If an optional ``version`` field is omitted from
a URL, the given Dandiset's most recent published version will be used if it
has one, and its draft version will be used otherwise.
Accepted resource identifier patterns:
- …
```
=> clarify resource identifier docs

dandi/tests/data/dandiarchive-docker/docker-compose.yml
We've added a new env var during the [embargo re-design](https://github.com/dandi/dandi-archive/pull/1890), and integration tests to that branch as well as master (once it's merged), will fail until this PR is merged.
=> Add DJANGO_DANDI_DEV_EMAIL env var to archive tests

.github/workflows/lint.yml, tox.ini
=> ENH: add/use codespell-project/codespell-problem-matcher to annotate PRs on where typos added

dandi/cli/cmd_download.py, dandi/dandiarchive.py
Original --help is too long and a little more inconsistent  -- the "#" are shell script construct and generally not used to demarkate anything there, so kind no point to have/look odd
Here is how it would look now
```shell
❯ dandi download --help
Usage: dandi download [OPTIONS] [URL]...
Download files or entire folders from DANDI.
RESOURCE ID/URLS:
dandi commands accept URLs and URL-like identifiers called <resource  ids>
in the following formats for identifying Dandisets, assets, and  asset
collections.
Text in [brackets] is optional.  A server field is a base API or GUI URL
for a DANDI Archive instance.  If an optional ``version`` field is  omitted
from a URL, the given Dandiset's most recent published version  will be
used if it has one, and its draft version will be used otherwise. …
```
=> Slight tune up to formatting of examples etc to harmonize appearance/make shorter

setup.cfg, tox.ini
We recently started to encounter stalling test runs which lead to hours of stalled operation.  Hopefully this would lead to failed test instead of a stall
TODOs:
=> ENH: add timeout of 300 (5 minutes) to any test running

dandi/dandiapi.py
Closes #1408.
Here's what was going on:  Occasionally, requests to S3 to upload a Zarr entry fail with a 500 status due to an internal error on S3's end, causing `dandi-cli` to retry the request.  When it retries the request, it calls `session.request()` again, passing in the same arguments as before, which include an open filehandle for reading the Zarr entry from disk.  However, the filehandle was already read to the end on the initial request (the one that resulted in a 500); thus, although `requests`'s `super_len()` obtains the correct value for the file's length, it then subtracts the filehandle's current position (the end of the file) from this length to get the number of bytes that would be produced by reading from the current position to the end of file: zero — and, as previously …
=> Rewind filehandle request bodies before retrying requests

dandi/download.py, dandi/tests/test_download.py
Individual commits have more description.
Closes: #1407 . @kabilar could you please check if works for you ok'ish?
edit 1: I think initial OPT commit is not entirely complete -- somewhere in the sandwich of all the generators there is still waiting  for an iterable to exhaust itself.
=> OPT+RF of zarr downloads: do not wait for full files listing + compute %done from total zarr size

dandi/dandiapi.py, dandi/tests/test_dandiapi.py
Closes #1452
See individual commits for more description/rationale.
Related:
- https://github.com/AllenInstitute/openscope_databook/pull/399
=> Normalize path while requesting list of assets from the server

setup.cfg
Per @jjnesbitt's advice [here](https://github.com/dandi/dandi-archive/issues/1975#issuecomment-2223977835)
Note that I have added the "release" tag to this PR in order to get this restriction out to users soon.
=> Temporarily restrict dandischema requirement to `< 0.10.2`

setup.cfg
This reverts commit ccf43297da2c505dc6bba21c8b551a0404d7e234.
Now that https://github.com/dandi/dandi-archive/issues/1975 has been closed as resolved.
=> Revert "Temporarily restrict dandischema requirement to `< 0.10.2`"

tox.ini
Broken on Python 3.8: https://github.com/python/mypy/pull/17543
=> Do not use mypy 1.11.0

dandi/cli/cmd_download.py, dandi/cli/tests/test_download.py, dandi/dandiarchive.py, dandi/download.py, dandi/tests/test_download.py, docs/source/cmdline/download.rst
=> Add `--preserve-tree` option to `dandi download`

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/test.yml, .github/workflows/typing.yml
This reverts commit b9c726d21a67a685bf7ac04b50984d0e418e70a8.
This should no longer be necessary as of the release of setuptools 72.1.0 within the last half-hour.
=> Revert "Unbreak vcrpy install"

dandi/cli/cmd_download.py, dandi/download.py, dandi/tests/test_download.py, docs/source/cmdline/download.rst
=> Fix handling of `--preserve-tree` for asset ID-only URLs

CHANGELOG.md
=> Fix one insignificant typo in CHANGELOG

dandi/move.py
In order to deal with embargoed Dandisets
Closes #1478.
=> move: Immediately authenticate client after creation

dandi/metadata/util.py, dandi/tests/test_metadata.py
=> BF: use correct variable in exception upon unknown how to handle value of "species"

.github/workflows/test.yml, dandi/tests/fixtures.py
=> Dump audit table to file specified by `DANDI_TESTS_AUDIT_CSV` envvar

dandi/organize.py, setup.cfg
Individual commits have more information in their description.
Overall it 
- Fixes #1494 
- Improves logging of problems in organize while loading metadata
I have  bundled all the fixes etc so we could return back our CI to green (happen there is more to fix) and release!
=> Disallow hdmf 3.14.4, make organize to not parallelize for a single file, log information about all exceptions while reading metadata for organize

.github/workflows/test.yml
Fixes https://github.com/dandi/dandi-cli/issues/1503
=> Switch to python 3.9 in dev-deps CI matrix run since dev deps are now beginning to drop Python 3.8 which is EOL soon

dandi/dandiarchive.py, dandi/tests/test_helptext.py
Fixes https://github.com/dandi/dandi-cli/issues/1501
```
$ dandi ls --help
Usage: dandi ls [OPTIONS] PATH|URL
List .nwb files and dandisets metadata.
The arguments may be either resource identifiers or paths to local
files/directories.
RESOURCE ID/URLS:
dandi commands accept URLs and URL-like identifiers called <resource  ids>
in the following formats for identifying Dandisets, assets, and  asset
collections.
Text in [brackets] is optional.  A server field is a base API or GUI URL
for a DANDI Archive instance.  If an optional ``version`` field is  omitted
from a URL, the given Dandiset's most recent published version  will be
used if it has one, and its draft version will be used otherwise.
Accepted resource identifier patterns:
- DANDI:<dandiset id>[/<version>]
- …
```
=> Fixup URI scheme rendering in --help output

dandi/pynwb_utils.py
=> Use "cache_spec:False" in our copy_nwb_file helper while exporting NWB copy

dandi/cli/command.py, dandi/download.py
hopefully would be in assist to troubleshoot issues with downloads, like the one now reported by @Kevancic on slack
=> ENH: log dandischema version and ensure we log (consistently) path for log messages in download

dandi/cli/tests/test_service_scripts.py, dandi/support/tests/test_iterators.py, dandi/tests/test_metadata.py
Rationale: we need to bring CI into more stable operation and then see how to address them properly
TODOs
=> Add xfail marks for some tests: test_nwb2asset_remote_asset, test_reextract_metadata, test_IteratorWithAggregation

.github/workflows/docs.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/typing.yml, .readthedocs.yaml, setup.cfg
Fixes https://github.com/dandi/dandi-cli/issues/1503
=> Drop claiming support and testing against EOL Python 3.8

dandi/pynwb_utils.py, dandi/tests/fixtures.py
re: https://github.com/con/validation/issues/1#issuecomment-2391975295
PyNWB reports a list of [HDMF validator Error objects](https://github.com/hdmf-dev/hdmf/blob/dev/src/hdmf/validate/errors.py#L19).
- Enhance pynwb validator output to report the path within the file and separate the reason (message) from the rest of the error.
- Fix typo "pywnb" -> "pynwb"
=> Enhance pynwb validation parsing to report the path within the file, fix pynwb typo

DEVELOPMENT.md
dandi-api does forward to dandi-archive, but still nice to have correct
=> fix: replace dandi-api link with dandi-archive

dandi/cli/tests/test_instances.py, dandi/consts.py, dandi/tests/test_dandiarchive.py, dandi/utils.py, docs/source/cmdline/instances.rst
Relates to https://github.com/dandi/dandi-cli/issues/1517
Follow-up of https://github.com/dandi/dandi-cli/pull/1519 -- used a different fork since tags were not copied over in the prior fork in https://github.com/dandi/dandi-cli/pull/1519
Cc @kabilar 
Steps to properly test:
1. `pip uninstall dandi -y` to remove DANDI CLI locally (can use a `venv` too if desired)
2. `pip install -e git+https://github.com/lincbrain/dandi-cli.git@ak-linc#egg=dandi` -- reference my forked branch here as the `dandi` CLI version
3. Made a Dandiset on LINC: https://lincbrain.org/dandiset/000045
4. Run `dandi download https://lincbrain.org/dandiset/000045/draft` -- the CLI should prompt for an API value here
5. I copied over an NWB into the `000045` folder
6. Run  `dandi upload -i linc`
7. Observe files present …
=> Include LINC API as a supported instance type for DANDI CLI

DEVELOPMENT.md, dandi/cli/command.py, dandi/cli/tests/test_service_scripts.py, dandi/dandiapi.py, dandi/download.py, dandi/tests/test_download.py, setup.cfg
It was originally developed as part of the PR but derailed into fixing/robustifying download functionality. So sits on top of 
- #1499
TODOs
-  ~~possibly fold in here~~ fixup for download to do full file checksumming if download was resumed: https://github.com/dandi/dandi-cli/issues/1528
=> download: more consistent and exhaustive logging, new `DANDI_DEVEL_AGGRESSIVE_RETRY` mode, respect (?) Retry-After

dandi/tests/data/dandiarchive-docker/docker-compose.yml
Closes: https://github.com/dandi/dandi-cli/issues/1488
See: https://github.com/celery/billiard/pull/417
@asmacdo please verify that it resolves the issue for you too
TODOs
- after accepted here, we better propose similar one against dandi-archive's compose recipes. In all likeliness situation would be similar there.
=> Specify custom ulimit on nofiles to prevent infinite loop by billiard

dandi/metadata/util.py
OnePhotonSeries is a newer data type, which is why it was not included in the original list
=> add one photon to metadata dict

dandi/tests/data/dandiarchive-docker/docker-compose.yml
- 855845303901bd17a53d6c784c6cc5e5c2b1e1e9 
Wed Dec 21 16:49:05 2022 -0500 
Add more detailed logging to development postgres
- b3ba0e8ab15a54b6d592a84d5c155c3ed6ee0390
Mon Oct 3 18:30:30 2022 -0400
Unpin minio docker image and update env vars
Unfortunately it does not resolve
- https://github.com/dandi/dandi-cli/issues/1488
for me but IMHO the right thing to do.
=> tests: update tests docker-compose with few changes from dandi-archive

dandi/dandiapi.py
=> Fix `PrivateAttr` usage

dandi/download.py, dandi/tests/test_download.py
=> Refactor some download code for readability + ensure that we checksum resumed downloads

dandi/metadata/util.py
Reference: http://purl.obolibrary.org/obo/NCBITaxon_10047
=> Add Meriones unguiculatus to species list

dandi/download.py, dandi/tests/test_download.py
=> Do fail (raise Exception, CLI has non-0 exit) download if any of downloads fail

dandi/metadata/util.py, dandi/tests/test_metadata.py
Addressing user report on Slack.
Apparently (thus checking with @satra) we were checking for URLs and only for "common names", not proper long names. It is surprising that the problem manifested only now then!
=> BF: do allow for user to specify a proper full name for "species" in metadata 

dandi/download.py
Somehow, with some prior version of the code, but we did get this assertion triggered as shown in
https://github.com/dandi/dandi-cli/issues/1549#issuecomment-2537027028 although it remains unclear how that could have happened if type checking is correct since we must not end up there with None or even 0.
Unfortunately with a regular assert we just get an announcement of the fact and no details.  After this change we hope to be able to see more details which might hint on the original issue.
=> download: provide description for an assertion error on attempts_allowed_or_not

dandi/cli/base.py
@Kevancic  reported a crash where logs where pretty much useless as on the source/reason for exception:
```
2024-12-11T18:28:38-0500 [DEBUG   ] dandi 1351865:139891061004032 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS01_stain-Calretinin_SPIM.ome.zarr/0/1/51/23 - verified that has correct md5 5f7119e7acfa30675994984323f9632e
2024-12-11T18:28:38-0500 [DEBUG   ] dandi 1351865:139894478612224 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS01_stain-Calretinin_SPIM.ome.zarr/0/1/51/27 - verified that has correct md5 e2e128cea135ab4d19df53208c3d649e
2024-12-11T18:28:38-0500 [DEBUG   ] dandi 1351865:139891086182144 sub-I48/ses-SPIM/micr/sub-I48_ses-SPIM_sample-BrocaAreaS01_stain-Calretinin_SPIM.ome.zarr/0/1/51/26 - verified that has correct md5 …
```
=> enh: log exception info (at debug) when we catch an exception in map_to_click handler

.github/workflows/test.yml, README.md, dandi/cli/cmd_instances.py, dandi/cli/command.py, dandi/cli/tests/data/update_dandiset_from_doi/biorxiv.json, dandi/cli/tests/data/update_dandiset_from_doi/elife.json, dandi/cli/tests/data/update_dandiset_from_doi/jneurosci.json, dandi/cli/tests/data/update_dandiset_from_doi/nature.json, dandi/cli/tests/data/update_dandiset_from_doi/neuron.json, dandi/conftest.py, dandi/dandiapi.py, dandi/dandiarchive.py, dandi/delete.py, dandi/download.py, dandi/exceptions.py, dandi/files/__init__.py, dandi/files/bases.py, dandi/files/zarr.py, dandi/organize.py, dandi/tests/fixtures.py, dandi/tests/test_delete.py, docs/design/python-api-1.md, docs/source/cmdline/dandi.rst, docs/source/cmdline/instances.rst, docs/source/modref/dandiapi.rst, docs/source/modref/index.rst, docs/source/ref/urls.rst, setup.cfg
=> Update docs to generalize from `DANDI Archive` to `DANDI instance`

dandi/download.py
=> Continue retrying downloads on retriable statuses

README.md, dandi/__init__.py
=> Update URL for DANDI Docs

.github/workflows/docs.yml, .readthedocs.yaml
The docs builds have been failing in CI for a while, always(?) due to pip giving up after excessive backtracking while trying to resolve dependencies. I tested out the following failing command from a recent CI run:
```
pip install 'anys~=0.2' 'bidsschematools~=0.7.0' click-didyoumean 'click>=7.1' coverage 'dandischema<0.12,>=0.9.0' 'etelemetry>=0.2.2' fasteners 'fscacher>=0.3.0' 'hdmf!=3.14.4,!=3.5.0' humanize 'interleave~=0.1' joblib 'keyring!=23.9.0' keyrings.alt 'nwbinspector!=0.4.32,>=0.4.28' opencv-python packaging platformdirs pycryptodomex 'pydantic~=2.0' 'pynwb!=1.1.0,!=2.3.0,>=1.0.3' 'pyout!=0.6.0,>=0.5' pytest pytest-cov pytest-mock pytest-rerunfailures pytest-timeout python-dateutil 'requests~=2.20' 'responses!=0.24.0,!=0.25.5' 'ruamel.yaml<1,>=0.15' semantic-version tenacity …
```
=> Use Python 3.10 to build docs

setup.cfg
Fixes #1463
Edit:
~We encountered this issue again today with `dandi==0.66.4` so I suggest that we pin to the latest `dandischema` version.~
~Error message:~
~$ dandi upload -i linc <path_to_ome_zarr>~
~Error: Server requires schema version 0.6.8; client only supports 0.6.9. You may need to upgrade dandi and/or dandischema~
cc @aaronkanzer @dstansby
=> Pin `dandischema` to require the latest `schema` version

.github/workflows/update-year.yml, LICENSE, docs/source/conf.py
related issue filed
- https://github.com/FantasticFiasco/action-update-license-year/issues/626
=> Do specify our copyright in LICENSE file, unify name with dandiarchive.org, make year auto update in docs

.github/workflows/test.yml, setup.cfg
=> Add Python 3.13 as supported version

.github/workflows/labels.yml
Ready for review, ~but not ready for merge.~
=> Enforce usage of auto (release) labels

dandi/pynwb_utils.py, dandi/tests/fixtures.py, dandi/tests/test_files.py
=> Fix support for pynwb v3 which has changed API slightly

dandi/download.py
In the logs provided for https://github.com/dandi/dandi-cli/issues/1581 I spotted lots of instances of log message due to
extra = self.items_summary.size - active
if extra < 0:
lgr.debug("Extra size %d < 0 -- must not happen", extra)
where we check difference between what is known/planned to be downloaded and what was downloaded so far.
Then I spotted that we reported  GBs for dandiset.yaml
(dandi) yoh@typhon:/data/tmp/yoh/dandi$ dandi download   -e refresh --path-type glob -J5:10 --preserve-tree 'dandi://DANDI/000026/sub-I58/ses-Hip-CT/micr/*.zarr'
PATH                                                                     SIZE      DONE            DONE% CHECKSUM STATUS    MESSAGE
000026/dandiset.yaml                                                     1.7 GB …
=> BF: do not provide size for dandiset.yaml (and definetely not mtime for the size)

.autorc, .github/workflows/release.yml
Bits are taken from http://github.com/brechtm/citeproc-py for which bits were taken from somewhere else as well.
Needed to release and realized that we do not do that upon dispatch yet here
=> Add ability to release upon workflow dispatch

dandi/tests/data/dandiarchive-docker/docker-compose.yml
Related: https://github.com/dandi/dandi-archive/pull/2205
=> Add Dandi admin email setting

dandi/cli/tests/test_cmd_ls.py, setup.cfg
- submitted https://github.com/bids-standard/bids-specification/pull/2085
=> Upgrade bidsschematools to be of 1.x series

dandi/metadata/util.py
This PR closes #1600. See the individual commit for details.
=> Remove deprecated use of Pydantic per Pydantic 2.11

dandi/download.py, dandi/tests/test_download.py
See individual commits for more information.
=> Download: make it retry more times and log the first error from many

dandi/cli/tests/test_cmd_validate.py, dandi/files/bases.py, dandi/files/bids.py, dandi/files/zarr.py, dandi/organize.py, dandi/pynwb_utils.py, dandi/tests/test_files.py, dandi/tests/test_validate.py, dandi/utils.py, dandi/validate.py, dandi/validate_types.py, setup.cfg
Ref:
- https://github.com/con/validation/issues/1
and result of our chat with @candleindark while also reviewing results of linkml validation over dandisets:
- https://github.com/dandi/dandisets-linkml-status/blob/temp-with-error-locations/dandi-reports/summary.md
Notes/TODOs:
- BREAKING CHANGE: 
- we replaced `ValidationOrigin.bids_version` to more generic `Origin.standard` + `Origin.standard_version`
- We renamed `ValidationOrigin.name` to `Origin.validator` and `ValidationOrigin.version` to `Origin.validator_version`
- `Severity.HINT`, `Severity.WARNING`, and `Severity.ERROR` now have value of `20`, `30`, and `40` respectively instead of `1`, `2`, and `3`.
- Introduce `Origin.type` to indicate the type of the origin of a validation result.
- We made the `ValidationResult` model into a …
=> Overhauling validation results to get them closer to cover different types of validators

dandi/files/bids.py
we already demand bidsschematools ~1.0 so if we are to follow the comment -- we should be fine.  But also -- bids_paths seems to be not used (since 45209e2ae8b65492521838632237fd0bec3000c0 awhile back) so it was dead code to start with.
=> Remove obsolete (without effect) piece of code in bids.py for validation

dandi/validate.py
This PR closes https://github.com/dandi/dandi-cli/issues/1617.
This solution is a bit awkward in my opinion, but it fixes the problem without overhaul of how validation is done in dandi-cli.
=> Deduplicate validation results yield from `validate.validate()`

setup.cfg
refs:
- https://github.com/pallets/click/issues/2911
- https://github.com/dandi/dandi-cli/issues/1627
=> BF(workaround): disallow click 8.2.0 due to regression

dandi/dandiarchive.py, dandi/tests/test_dandiarchive.py
We long migrated to just dandiarchive.org . Excessive use of gui. resulted in too many redirects and seems like likely heroku limiting our requests thus tests some times failing to get all the way to redirected site. But since we no longer even use gui.  domain, there is no need to test it. I also adjusted test to exclude /# from URL since also no longer there and would be redirected/handled.
I would consider it
- Closes #1598
Also added one more change to test redirect actually against this gui. (but once) instead of bit.ly -- hopefully would be more robust on windows.
=> Stop extensively test no longer used gui.dandiarchive.org, retry HEAD (redirects) upon requests.ConnectionError

dandi/organize.py
I remembered doing this and then found patch within dandi-feedstock , but never submitted here as a fix, but we ran into it within dandischema recently (thus attn to @candleindark )
=> Workaround: catch AttributeError while formatting exception

setup.cfg
This is to undo a change brought by https://github.com/dandi/dandi-cli/pull/1630 Now that dandiarchive is using the new JSON schema.
This PR closes https://github.com/dandi/dandi-cli/issues/1635.
=> Unrestrict `dandischema` version

setup.cfg
For a different repository we need to use Zarr v3 and the `dandi-cli`.  Now that #1609 is resolved, could we unpin the Zarr dependency here?
cc @balbasty @calvinchai @satra @ayendiki
=> Expand Zarr dependency to include version 3

dandi/metadata/nwb.py
Took a while to pin down the problem when uploading the BEP32 example data
I think there is still some recursion that occurs bouncing between NWB and BIDS validation, but it safely terminates without issue
Should still try to remove it, but the outright blocking issue was this line
=> Fix bug when running metadata extraction on BIDS with NWB

dandi/cli/tests/test_cmd_validate.py, dandi/tests/test_fixtures.py, dandi/tests/test_organize.py, dandi/tests/xfail.py
See e.g.
https://github.com/dandi/dandi-cli/actions/runs/17147460699/job/48646355661
ERROR dandi/cli/tests/test_cmd_validate.py::test_validate_nwb_path_grouping - AssertionError: Error: No module named '_posixsubprocess'
ERROR dandi/tests/test_fixtures.py::test_organized_nwb_dir2 - AssertionError: Error: No module named '_posixsubprocess'
where it is due to not us but 'multiprocessing'
File "C:\hostedtoolcache\windows\Python\3.13.7\x64\Lib\multiprocessing\resource_tracker.py", line 261, in _send
self._ensure_running_and_write(msg)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
File "C:\hostedtoolcache\windows\Python\3.13.7\x64\Lib\multiprocessing\resource_tracker.py", line 220, in _ensure_running_and_write
self._launch()
~~~~~~~~~~~~^^
File …
=> BF: announce two tests xfail on windows python 3.13
